
This notebook merges all processed modalities into a unified patient-level dataset.

Inputs:
- Clinical processed dataset
- Genomic processed dataset
- Follow-up processed dataset
- Histopathology feature embeddings

Outputs:
- multimodal_master_dataset.csv

Purpose:
Create the final patient-level dataset used for model development.

##Imports

In [138]:
# ============================================================
# IMPORT LIBRARIES
# ============================================================

import os
import glob
import numpy as np
import pandas as pd

from google.colab import drive

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

##Mount Google Drive

In [139]:
# ============================================================
# CONNECT GOOGLE DRIVE
# ============================================================

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##Define Project Paths

In [140]:
# ============================================================
# PROJECT PATHS
# ============================================================

BASE_DIR = "/content/drive/MyDrive/TCGA_BRCA"

GENOMIC_PATH = os.path.join(
    BASE_DIR,
    "genomic_processed",
    "genomic_processed.csv"
)

CLINICAL_PATH = os.path.join(
    BASE_DIR,
    "clinical_processed",
    "clinical_processed.csv"
)

FOLLOWUP_PATH = os.path.join(
    BASE_DIR,
    "followup_processed",
    "followup_processed.csv"
)

FEATURE_DIR = os.path.join(
    BASE_DIR,
    "Features"
)

SAVE_DIR = os.path.join(
    BASE_DIR,
    "multimodal_dataset"
)

os.makedirs(
    SAVE_DIR,
    exist_ok=True
)

print("Project directory ready.")

Project directory ready.

##Load Clinical, Genomic and Follow-up

In [141]:
# ============================================================
# LOAD TABULAR DATA
# ============================================================

clinical = pd.read_csv(CLINICAL_PATH)

genomic = pd.read_csv(GENOMIC_PATH)

followup = pd.read_csv(FOLLOWUP_PATH)

print("="*70)
print("DATASETS LOADED")
print("="*70)

print("Clinical :", clinical.shape)
print("Genomic  :", genomic.shape)
print("FollowUp :", followup.shape)

======================================================================
DATASETS LOADED
======================================================================
Clinical : (1097, 21)
Genomic  : (1093, 1001)
FollowUp : (1095, 3)

##Load Histopathology Feature Metadata

In [142]:
# ============================================================
# LOAD FEATURE METADATA
# ============================================================

metadata_path = os.path.join(
    FEATURE_DIR,
    "features_metadata.csv"
)

metadata = pd.read_csv(metadata_path)

print("="*70)
print("FEATURE METADATA")
print("="*70)

print(metadata.shape)

display(metadata.head())

======================================================================
FEATURE METADATA
======================================================================
(369, 7)

,patient_id,num_patches,feature_shape,num_patches_total,num_patches_accepted,num_patches_rejected,num_errors
0,a1b58cd0-559e-467d-a193-96602cd3306f,12697.0,"(12697, 512)",NaN,NaN,NaN,NaN
1,997dbd8f-9f16-4fc2-8627-d29ee0d74ebe,1989.0,"(1989, 512)",NaN,NaN,NaN,NaN
2,9132985f-ecd8-4a67-ba7b-63902801fba6,9047.0,"(9047, 512)",NaN,NaN,NaN,NaN
3,ce77af22-10b7-4480-9c93-015970268455,13609.0,"(13609, 512)",NaN,NaN,NaN,NaN
4,fcc84daa-5e54-4773-88a8-aa76727ffb6c,10695.0,"(10695, 512)",NaN,NaN,NaN,NaN

##Inspect Metadata Columns

In [143]:
# ============================================================
# METADATA INFORMATION
# ============================================================

print("="*70)
print("METADATA COLUMNS")
print("="*70)

for col in metadata.columns:
    print(col)

======================================================================
METADATA COLUMNS
======================================================================
patient_id
num_patches
feature_shape
num_patches_total
num_patches_accepted
num_patches_rejected
num_errors

##Load GDC metadata JSON

In [144]:
# ============================================================
# LOAD GDC METADATA CART JSON
# ============================================================

import json
import pandas as pd
import os


METADATA_PATH = (
    "/content/drive/MyDrive/TCGA_BRCA/"
    "metadata.cart.2026-07-20.json"
)


print("="*70)
print("LOADING GDC METADATA CART")
print("="*70)


with open(METADATA_PATH, "r") as f:
    metadata_json = json.load(f)


print("Total metadata records:")
print(len(metadata_json))


print("\nFirst record keys:")
print(metadata_json[0].keys())

======================================================================
LOADING GDC METADATA CART
======================================================================
Total metadata records:
956

First record keys:
dict_keys(['data_format', 'access', 'associated_entities', 'file_name', 'md5sum', 'file_id', 'data_type', 'submitter_id', 'data_category', 'state', 'experimental_strategy', 'file_size'])

##Convert JSON to dataframe

In [145]:
# ============================================================
# CONVERT METADATA TO DATAFRAME
# ============================================================


metadata_df = pd.json_normalize(
    metadata_json
)


print("="*70)
print("METADATA DATAFRAME")
print("="*70)


print("Shape:")
print(metadata_df.shape)


print("\nColumns:")

for col in metadata_df.columns:
    print(col)


display(
    metadata_df.head()
)

======================================================================
METADATA DATAFRAME
======================================================================
Shape:
(956, 13)

Columns:
data_format
access
associated_entities
file_name
md5sum
file_id
data_type
submitter_id
data_category
state
experimental_strategy
file_size
annotations

,data_format,access,associated_entities,file_name,md5sum,file_id,data_type,submitter_id,data_category,state,experimental_strategy,file_size,annotations
0,SVS,open,[{'entity_submitter_id': 'TCGA-E2-A14P-01Z-00-...,TCGA-E2-A14P-01Z-00-DX1.663B02FF-C64B-41A6-868...,22b18a6eea2790519592033b43f6f423,4730b23e-aea1-49a2-ba63-2231fd88b592,Slide Image,TCGA-E2-A14P-01Z-00-DX1_slide_image,Biospecimen,released,Diagnostic Slide,1597343893,NaN
1,SVS,open,[{'entity_submitter_id': 'TCGA-A7-A0CD-01Z-00-...,TCGA-A7-A0CD-01Z-00-DX1.F045B9C8-049C-41BF-843...,d148f6d71ac283e653c29ee7e77b2f23,554855d7-4e21-406b-8f9f-458b1e7c89c9,Slide Image,TCGA-A7-A0CD-01Z-00-DX1_slide_image,Biospecimen,released,Diagnostic Slide,280966835,"[{'entity_submitter_id': 'TCGA-A7-A0CD', 'note..."
2,SVS,open,[{'entity_submitter_id': 'TCGA-5L-AAT1-01Z-00-...,TCGA-5L-AAT1-01Z-00-DX1.F3449A5B-2AC4-4ED7-BF4...,12416cc41421ba836c7e11aad25594f4,4eec69ca-381b-4c17-b3e9-49492d71560e,Slide Image,TCGA-5L-AAT1-01Z-00-DX1_slide_image,Biospecimen,released,Diagnostic Slide,592769341,"[{'entity_submitter_id': 'TCGA-5L-AAT1', 'note..."
3,SVS,open,[{'entity_submitter_id': 'TCGA-A8-A09K-01Z-00-...,TCGA-A8-A09K-01Z-00-DX1.41B2DF5F-C0E1-43BB-BAA...,e984afa92734d962f2d34bdf7295c954,0dec98aa-fb71-4367-8d39-6a71ae06e442,Slide Image,TCGA-A8-A09K-01Z-00-DX1_slide_image,Biospecimen,released,Diagnostic Slide,1044914964,"[{'entity_submitter_id': 'TCGA-A8-A09K', 'note..."
4,SVS,open,[{'entity_submitter_id': 'TCGA-C8-A1HI-01Z-00-...,TCGA-C8-A1HI-01Z-00-DX1.C6D0F8B8-55ED-477F-BAF...,a40d272bed0d079189d2cce1a1db432e,1bf2c09e-854f-414f-9b5e-2ad8a5176abd,Slide Image,TCGA-C8-A1HI-01Z-00-DX1_slide_image,Biospecimen,released,Diagnostic Slide,933681451,"[{'entity_submitter_id': 'TCGA-C8-A1HI', 'note..."

##Check available patient identifiers

In [146]:
# ============================================================
# CHECK IDENTIFIER COLUMNS
# ============================================================


print("="*70)
print("IDENTIFIER COLUMNS")
print("="*70)


for col in metadata_df.columns:

    if (
        "id" in col.lower()
        or
        "case" in col.lower()
        or
        "submitter" in col.lower()
        or
        "patient" in col.lower()
    ):
        print(col)

======================================================================
IDENTIFIER COLUMNS
======================================================================
file_id
submitter_id

##Load your Features folder

In [147]:
# ============================================================
# LOAD HISTOPATHOLOGY FEATURES
# ============================================================


FEATURE_DIR = (
    "/content/drive/MyDrive/TCGA_BRCA/Features"
)


feature_files = []


for f in os.listdir(FEATURE_DIR):

    if f.endswith(".npy"):
        feature_files.append(
            f.replace(".npy","")
        )


features_uuid = pd.DataFrame(
    {
        "file_uuid": feature_files
    }
)


print("="*70)
print("FEATURE UUIDS")
print("="*70)


print(
    "Number of feature files:",
    len(features_uuid)
)


display(
    features_uuid.head()
)

======================================================================
FEATURE UUIDS
======================================================================
Number of feature files: 372

                              file_uuid
0  a1b58cd0-559e-467d-a193-96602cd3306f
1  997dbd8f-9f16-4fc2-8627-d29ee0d74ebe
2  9132985f-ecd8-4a67-ba7b-63902801fba6
3  ce77af22-10b7-4480-9c93-015970268455
4  fcc84daa-5e54-4773-88a8-aa76727ffb6c

##Compare feature UUIDs with metadata UUIDs

In [148]:
# ============================================================
# MATCH FEATURE UUIDS WITH GDC FILE UUID
# ============================================================


print("="*70)
print("MATCHING FEATURE UUIDS WITH GDC METADATA")
print("="*70)


metadata_ids = set(
    metadata_df["file_id"]
    .astype(str)
)


features_uuid["found_in_metadata"] = (
    features_uuid["file_uuid"]
    .isin(metadata_ids)
)



print(
    features_uuid["found_in_metadata"]
    .value_counts()
)


print("\nMatching percentage:")

print(
    features_uuid["found_in_metadata"]
    .mean()*100
)

======================================================================
MATCHING FEATURE UUIDS WITH GDC METADATA
======================================================================
found_in_metadata
True    372
Name: count, dtype: int64

Matching percentage:
100.0

##Extract TCGA patient IDs

In [149]:
# ============================================================
# CREATE SLIDE UUID -> PATIENT ID MAPPING
# ============================================================


print("="*70)
print("CREATING PATHOLOGY PATIENT MAPPING")
print("="*70)



mapping = metadata_df[
    [
        "file_id",
        "submitter_id"
    ]
].copy()



# Extract TCGA patient barcode

mapping["patient_id"] = (
    mapping["submitter_id"]
    .str.extract(
        r"(TCGA-[A-Z0-9]{2}-[A-Z0-9]{4})"
    )[0]
)



print("Total slides:")
print(len(mapping))


print("\nUnique patients:")
print(
    mapping["patient_id"]
    .nunique()
)


display(
    mapping.head()
)

======================================================================
CREATING PATHOLOGY PATIENT MAPPING
======================================================================
Total slides:
956

Unique patients:
901

,file_id,submitter_id,patient_id
0,4730b23e-aea1-49a2-ba63-2231fd88b592,TCGA-E2-A14P-01Z-00-DX1_slide_image,TCGA-E2-A14P
1,554855d7-4e21-406b-8f9f-458b1e7c89c9,TCGA-A7-A0CD-01Z-00-DX1_slide_image,TCGA-A7-A0CD
2,4eec69ca-381b-4c17-b3e9-49492d71560e,TCGA-5L-AAT1-01Z-00-DX1_slide_image,TCGA-5L-AAT1
3,0dec98aa-fb71-4367-8d39-6a71ae06e442,TCGA-A8-A09K-01Z-00-DX1_slide_image,TCGA-A8-A09K
4,1bf2c09e-854f-414f-9b5e-2ad8a5176abd,TCGA-C8-A1HI-01Z-00-DX1_slide_image,TCGA-C8-A1HI

##Match Histopathology Features to Patient IDs

In [150]:
# ============================================================
# MERGE FEATURES WITH PATIENT IDS
# ============================================================


feature_patient_mapping = (
    features_uuid
    .merge(
        mapping,
        left_on="file_uuid",
        right_on="file_id",
        how="left"
    )
)



print("="*70)
print("FEATURE PATIENT MAPPING")
print("="*70)


print(
    feature_patient_mapping.shape
)


print(
    "Missing patients:"
)

print(
    feature_patient_mapping["patient_id"]
    .isna()
    .sum()
)



display(
    feature_patient_mapping.head()
)

======================================================================
FEATURE PATIENT MAPPING
======================================================================
(372, 5)
Missing patients:
0

,file_uuid,found_in_metadata,file_id,submitter_id,patient_id
0,a1b58cd0-559e-467d-a193-96602cd3306f,True,a1b58cd0-559e-467d-a193-96602cd3306f,TCGA-E2-A1LB-01Z-00-DX1_slide_image,TCGA-E2-A1LB
1,997dbd8f-9f16-4fc2-8627-d29ee0d74ebe,True,997dbd8f-9f16-4fc2-8627-d29ee0d74ebe,TCGA-AC-A8OP-01Z-00-DX1_slide_image,TCGA-AC-A8OP
2,9132985f-ecd8-4a67-ba7b-63902801fba6,True,9132985f-ecd8-4a67-ba7b-63902801fba6,TCGA-AN-A0XP-01Z-00-DX1_slide_image,TCGA-AN-A0XP
3,ce77af22-10b7-4480-9c93-015970268455,True,ce77af22-10b7-4480-9c93-015970268455,TCGA-E9-A1R4-01Z-00-DX1_slide_image,TCGA-E9-A1R4
4,fcc84daa-5e54-4773-88a8-aa76727ffb6c,True,fcc84daa-5e54-4773-88a8-aa76727ffb6c,TCGA-AC-A2BM-01Z-00-DX1_slide_image,TCGA-AC-A2BM

##Keep only patients that actually have pathology embeddings

In [151]:
# ============================================================
# KEEP ONLY PATIENTS WITH PATHOLOGY FEATURES
# ============================================================

print("=" * 70)
print("PATIENTS WITH HISTOPATHOLOGY FEATURES")
print("=" * 70)

pathology_patients = (
    feature_patient_mapping[
        ["patient_id", "file_uuid"]
    ]
    .drop_duplicates()
    .copy()
)

print("Patients with pathology features:")
print(pathology_patients.shape[0])

display(pathology_patients.head())

======================================================================
PATIENTS WITH HISTOPATHOLOGY FEATURES
======================================================================
Patients with pathology features:
372

     patient_id                             file_uuid
0  TCGA-E2-A1LB  a1b58cd0-559e-467d-a193-96602cd3306f
1  TCGA-AC-A8OP  997dbd8f-9f16-4fc2-8627-d29ee0d74ebe
2  TCGA-AN-A0XP  9132985f-ecd8-4a67-ba7b-63902801fba6
3  TCGA-E9-A1R4  ce77af22-10b7-4480-9c93-015970268455
4  TCGA-AC-A2BM  fcc84daa-5e54-4773-88a8-aa76727ffb6c

##Merge clinical

In [152]:
# ============================================================
# MERGE CLINICAL DATA
# ============================================================

multimodal = pathology_patients.merge(
    clinical,
    on="patient_id",
    how="inner"
)

print("=" * 70)
print("AFTER CLINICAL MERGE")
print("=" * 70)

print(multimodal.shape)

======================================================================
AFTER CLINICAL MERGE
======================================================================
(372, 22)

##Merge genomic

In [153]:
# ============================================================
# MERGE GENOMIC DATA
# ============================================================

multimodal = multimodal.merge(
    genomic,
    on="patient_id",
    how="inner"
)

print("=" * 70)
print("AFTER GENOMIC MERGE")
print("=" * 70)

print(multimodal.shape)

======================================================================
AFTER GENOMIC MERGE
======================================================================
(369, 1022)

##Merge follow-up

In [154]:
# ============================================================
# MERGE FOLLOW-UP DATA
# ============================================================

multimodal = multimodal.merge(
    followup,
    on="patient_id",
    how="inner"
)

print("=" * 70)
print("AFTER FOLLOW-UP MERGE")
print("=" * 70)

print(multimodal.shape)

display(multimodal.head())

======================================================================
AFTER FOLLOW-UP MERGE
======================================================================
(369, 1024)

,patient_id,file_uuid,years_to_birth,Tumor_purity,pathologic_stage,pathology_T_stage,pathology_N_stage,pathology_M_stage,number_of_lymph_nodes,radiation_therapy,histological_type_infiltratinglobularcarcinoma,histological_type_medullarycarcinoma,histological_type_metaplasticcarcinoma,histological_type_mixedhistology(pleasespecify),histological_type_mucinouscarcinoma,"histological_type_other,specify",PAM50_Her2,PAM50_LumA,PAM50_LumB,race_blackorafricanamerican,race_white,ethnicity_nothispanicorlatino,CLEC3A,CPB1,SCGB2A2,SCGB1D2,TFF1,GSTM1,PIP,S100A7,MUCL1,CYP2B7P1,ANKRD30A,PRAME,CYP4Z1,KCNJ3,AGR3,HMGCS2,SERPINA6,TFAP2B,MUC6,DHRS2,SLC30A8,UGT2B11,VSTM2A,COL2A1,C4orf7,TAT,ADIPOQ,ADH1B,CALML5,GP2,MYBPC1,GABRP,KRT14,CEACAM5,MUC5B,TFF3,C1orf64,SOX10,GRIA2,KRT5,CRABP1,GSTT1,SYT13,STAC2,CST9,LTF,KRT6B,BMPR1B,KLK11,HOXB13,CYP2A6,FABP7,NPY1R,CEACAM6,GFRA1,CRISP3,ABCC11,C20orf114,CLCA2,KIF1A,PVALB,LRP2,TCN1,AGR2,OBP2B,CP,CGA,PGR,KCNC2,SLC34A2,OLFM4,KRT6A,KLK5,MUC16,CYP4F8,PROM1,BPIL1,KRT16,DSG3,FAM5C,MSLN,SLC5A8,A2ML1,CBLN2,SERPINA11,NLRP2,PIGR,PTPRT,AQP5,KRT81,ELF5,KRT17,CA9,VGLL1,BEX1,CST1,TUSC5,SLC6A4,LBP,KLK6,KLK10,CYP4Z2P,PPP1R1B,NXPH1,SLITRK6,KLHDC7A,LRRC31,ESR1,C10orf82,PPP2R2C,EEF1A2,SYT9,DCD,ANKRD30B,SCGB2A1,ORM1,CALML3,GRPR,FABP4,CHAD,TNNT1,CST5,SORCS1,MAGEA6,KLK7,ASCL1,MUC2,CLIC6,PDZK1,CDC20B,CXCL17,SLC6A14,RPS28,PEG10,DIO1,CARTPT,FOXI1,NBPF4,SPAG6,PYDC1,C7,SDR16C5,CASP14,CNTNAP2,ABCC8,WNK4,MUC15,CIDEC,LCN2,S100A7A,PPAN-P2RY11,SCUBE2,MIA,S100A8,ABCA12,SCGB3A1,PGLYRP2,FOLR1,DSC3,C2orf54,CAPN8,IGSF1,MSMB,CXCL13,S100A9,LRP1B,MAGEA3,SERPINA5,TMPRSS4,LY6D,TRH,SERPINB5,GLYATL2,SLC7A4,HS6ST3,SLC5A1,PON3,MMP1,ERBB4,SLC44A4,SFRP1,NBPF6,PLA2G2A,COL17A1,ALB,ZIC1,S100P,ROBO2,RIMS4,ORM2,CYP4F22,WIF1,NEK10,NCRNA00052,GLRA3,TMC5,ABCC13,IL20,ROPN1,PI16,LPPR3,ELOVL2,INSM1,TSPAN8,CCL19,SLC9A2,SLC7A2,LEP,PI3,LOC728606,FREM2,MS4A15,WFDC2,KNDC1,FAM3B,HGD,ATP6V0A4,WDR72,FGB,CAPN6,CHST8,ATP13A5,NKAIN1,TRPA1,SYT1,NCCRP1,FAM5B,PTPRZ1,ANXA8,CYP4B1,HORMAD1,VTCN1,FOXJ1,CCL21,SYTL5,KLK8,ACTL8,PKP1,CR2,GRB14,SPDYC,KRT15,PLIN1,AGTR1,CHGB,BCAS1,C16orf89,GLDC,TPRG1,BBOX1,TMPRSS6,GPD1,HOTAIR,CYP4X1,TUBA3D,ART3,SYT8,LRG1,GPR98,NAT1,CYP2A7,MS4A1,FSIP1,FAM196A,CIDEA,GSTA1,TRIM29,SLPI,PROL1,NDP,DLK1,CHIT1,ZIC2,FLJ45983,PAX7,ROPN1B,SOSTDC1,HEPACAM2,PPP4R4,PCSK1N,ALOX15B,PNMT,ATRNL1,IGDCC3,CST4,TF,MARCO,PSCA,MMP12,RGS22,ANXA8L2,DSG1,C2CD4A,SLC13A2,LOC100271831,GPR26,AKR7A3,ONECUT2,GABRB3,HOXC11,PRODH,GJB1,KRT23,KRT6C,RBM24,C1orf173,C19orf33,C3orf57,GRIK3,FOXA1,TRPV6,THRSP,UGT2B15,ARHGAP36,DARC,SAA2,SHISA9,KRT4,TMPRSS3,FUT3,VSIG2,IGJ,POF1B,PPP1R14C,SAA1,VIPR2,TPSG1,PRSS21,TDRD1,HBA1,PLIN4,TFPI2,KRT13,AREG,TTYH1,SLC26A3,SLC28A3,PLCH1,MMP13,CCNO,AR,DLX2,DKK1,CXADRP3,SYNPO2L,AFF3,ATP13A4,S100A2,AKR1B10,PI15,SPAG17,NTNG1,FAM83E,SBSN,PCDHA11,ANKRD43,ZNF385B,NPY5R,F7,HSD17B2,DCX,NELL2,MAPK4,FGG,PCDHA12,IYD,SOX2,MYT1,CACNG4,DCDC2,FAM83A,EPYC,ADCY5,TSIX,CHI3L2,PHGR1,PCDH10,WT1,SHISA2,KCNG1,PP14571,EDN3,HPX,RIMS2,COL11A1,CD177,TLX1,PCK1,GLYATL1,CYP4F11,SEZ6L,LOC642587,S100A1,TTC36,MMP7,PART1,NEURL,TBC1D3G,CNTFR,GABBR2,CRYM,TOX3,PPP1R1A,SCRG1,PLA2G2D,LGR6,RET,SLC15A1,ZFP57,SMOC1,HOXC10,TUBA3E,UGT2B28,MKRN3,HRASLS5,SLC6A11,CXCL14,CHGA,PLA2G3,KCNF1,RHCG,CHRDL1,TSPAN1,MKX,BCL11A,FBN3,MS4A8B,SLC6A15,NKX2-2,MAGEA1,FUT6,MAPT,CTNND2,CPLX2,AKR1C2,DOK7,UGT8,PCSK1,LOC389033,CECR2,APOD,OGN,RASAL1,DACH1,ABCC12,HP,TMEM40,MMP10,CPA6,ABCA8,FAT2,SCNN1G,DEFB1,LY6K,C2orf40,SCARA5,FGFBP1,NOVA1,CLGN,FGF10,SCGN,PIK3C2G,CCL18,RBP4,GRM4,TPSD1,ADAMTS15,CD79A,C1orf106,TNFSF12-TNFSF13,FLT3,AQP7,PAH,GPRIN2,PLIN5,NMU,IRX4,ADAMTS19,SHC4,CLSTN2,GATA4,GJB3,B3GNT3,FCRL5,TMEM132C,SLC1A1,EMX1,PCOLCE2,DLGAP1,PSAT1,MAOB,COL9A3,AFP,ADAM6,LOC339535,IRX1,LOC440905,SEMA3E,CD300LG,SERHL2,GNG4,CAPN9,MYO3B,LOC84740,PDZK1IP1,SLC44A5,CXorf61,DNALI1,HAPLN1,PAX2,SLC19A3,CD19,DLX1,SPDEF,C6,SERPINB2,MAGEA4,IL12RB2,UNC5A,CAPN13,CHRM1,COCH,PEG3,CKMT1A,TMEM213,FERMT1,SPINK8,SOX11,NELL1,PADI3,TNNI3,CXCL9,CHI3L1,PCDHA10,PTCHD1,FUT9,CA8,LOC145837,LRRC26,GAL,CWH43,CA12,DNER,RNF183,L1CAM,SLC27A6,STC2,DPYSL5,CDSN,ACTA1,TRIM58,PCDHA6,MAGEA2,TMEM45B,UBD,ADAMTS16,GATA5,FAM184B,DEGS2,PRG4,ANO5,C2orf72,HHIPL2,HPGD,FIBCD1,KRT7,C2orf82,PCDHA4,ALOX15,VWDE,EN1,DES,KCNK15,ACTG2,TP63,ST8SIA6,NTS,IGFALS,ZBTB16,LGALS12,ABCA13,C1orf168,B3GALT5,IDO1,CXCR2P1,GPX2,GPR110,DBC1,PTPN20B,EREG,KRT75,GRIA1,SPIB,NTRK3,SCUBE1,SAMD11,C1orf95,S100B,NKX2-5,TMEM150C,ANO3,TCL1A,VWA2,SLC27A2,LIN7A,ACE2,RASSF10,PEBP4,NCAM2,AMY1A,MAT1A,MAPK15,ATP6V1B1,XAGE1D,VSTM2L,NLRP5,ACTN2,CDH19,FAM3D,LRTM2,C8orf85,MGAM,KCNH1,SLC12A1,RTBDN,MLPH,LOC96610,DPY19L2P4,DNAJC12,CHST9,UGT2B4,SIX3,SP5,C10orf81,OSR1,SCAND3,KLK14,LONRF2,HOXC13,GPM6A,THBS4,MT1G,MYEOV,ARX,SCEL,CYP24A1,CLDN8,UPK1A,MAGEA12,TCAM1P,CACNG6,COL4A6,GRP,RIMS1,ADAMDEC1,BRSK2,GREB1,GPR12,RP1,PLP1,DNAH11,PRR15,CPA3,KCND3,CSAG3,POU2AF1,ZMAT4,FAM135B,CST2,LOC100128977,ABHD12B,AKR1B15,FAM83B,AK5,MUM1L1,RANBP3L,FLRT3,SCNN1B,ADCY2,CACNG1,SLC30A2,AP3B2,IL6ST,CALB2,PCDHA1,FOXD1,PHYHD1,TUBB2B,TIMP4,SPESP1,PNCK,CITED1,SERPINB7,SULT4A1,SUSD3,GAD1,CADM3,SELP,PLAC2,MNX1,ATP1A2,UGT1A6,GPR158,SMC1B,ALDH3B2,IVL,CACNA1H,PHF21B,TNS4,TYRP1,C1orf116,LOC150622,ADH1C,LOC389493,C19orf21,EGF,AQP9,KLK12,CD1A,LPAR3,TMEM145,GJB5,LOC100130148,ALDH1L1,PTX3,SLITRK5,MSI1,CXCL1,XDH,SCUBE3,ADCY1,CKMT1B,KCNK3,B4GALNT2,SIX1,GJB6,EHF,WDR17,ALOX12P2,KLK13,UPF0639,CORO6,DQX1,P2RY11,C21orf15,SCN7A,BMP7,PCSK2,ENTPD8,AGT,AMBP,GREB1L,ATP1A4,SLC16A6,RELN,PRSS12,HPN,RIC3,TMEM84,MMP3,LOC153328,LY6G6C,KCNE4,SLC35F3,TBX1,FGFR4,HOXB5,KLK4,AQP3,WISP3,LOC152225,C6orf141,CXCL5,MGC29506,PCDHA13,C6orf15,PITX1,CAPSL,HRASLS,KCNK2,NPW,C14orf180,SOX8,CES3,CAMK2B,CUX2,CT62,DUSP9,EPHA8,KRT31,NXNL2,RERGL,KIAA0125,ACMSD,TDRD9,FABP6,DAPL1,ADCYAP1,CYP4F12,CFB,GSDMC,KIF12,HMP19,KCNK1,BLK,WNT6,CLEC10A,RARRES1,CSN3,PCDHGB5,ARMC3,C1orf130,KRT86,CPA4,CHRDL2,TNFRSF17,GZMB,HRCT1,ITIH5L,LRAT,C4A,FAIM2,SERPINA3,GRIA4,TDRD12,LYPD6,COMP,CD38,PTPRN2,CRTAC1,TARP,FOSB,SMYD1,SMR3B,AKR1C1,C9orf152,NME5,LGALS7B,GPT,MT1A,IL33,RNF212,PRSS16,STEAP4,TPSB2,ACOX2,CHODL,CTSG,CNTN1,C4BPA,REEP6,CILP,KISS1R,TGM3,C8orf84,OXGR1,SRPK3,ARC,PRKAA2,IBSP,ATP1A3,CAMP,STK32B,IL7R,CCL28,SLC4A10,PGC,HS6ST2,AZGP1,PYY,BAIAP3,KIAA0408,MRAP,SFTPA2,FOXA3,CRHR1,MOGAT2,GPR87,CPNE4,GFRA3,CHRNA9,CCL14,TMEM139,ODZ2,SLIT1,NPY2R,ITGB6,GLB1L2,SPINK5,HMGCLL1,SNORD116-4,FGFR3,CRISPLD1,SPRR3,ABP1,LMO3,GZMK,LRRN1,RUNDC3A,LGALS7,ALG1L,EYA1,CD36,ACCN1,GGT6,ABCA4,IGSF21,BARX1,BPI,KLRG2,FAM189A1,PXDNL,ECEL1,FCER2,OGDHL,GABRE,TNN,PLEKHG4B,IL20RA,MUC13,SDK2,LTB,TNNT3,GNG13,LACRT,SYT5,C6orf223,KIAA0319,KLHDC7B,MESP1,MUC7,LEFTY2,KCNH2,CYP26A1,PCDH20,COL22A1,CST6,PCDHGB1,NRK,ZMYND10,FMO2,GDF15,CYP21A2,LAMC2,MAG,NRXN1,GRAMD2,PRSS33,FCRL3,PCP4L1,MAP7D2,LGR5,FXYD1,CES1,CDH7,VIT,PNPLA3,LEMD1,DPP10,HDC,IL6,CACNA2D1,ZPLD1,CCDC129,LDHC,LOC284379,KLHL1,C20orf85,CHRNB2,MMRN1,EDIL3,PEX5L,MLC1,psiTPTE22,BMP5,MAGEC2,CXCL11,PLA2G10,TGM5,CD207,COL11A2,SNAP25,CDCA7,CLDN10,OBP2A,ENHO,EPHA7,B3GAT1,COL10A1,CRLF1,DNAH5,DMKN,SLC1A6,PTGDS,TFCP2L1,ZIC5,CRYAB,EMILIN3,TNNT2,INA,event,survival_time
0,TCGA-E2-A1LB,a1b58cd0-559e-467d-a193-96602cd3306f,-1.343912,0.636328,2,2,1,0,-0.035909,1,False,False,False,False,False,False,True,False,False,True,False,True,0.263721,-1.267645,-1.359289,-1.636181,-1.000441,1.888609,1.489342,-0.364925,2.072394,-1.417470,0.770257,-0.951547,-0.418689,0.175216,-2.204608,2.376202,-0.908849,1.225710,1.911954,1.936378,-1.164419,2.674780,-0.794982,-0.789084,-1.145298,2.311160,-0.785761,-0.759443,0.047800,-0.684764,1.961438,-1.056166,-1.992519,-0.588714,-1.821005,0.197152,0.411802,-1.133525,-1.019018,-2.011747,-1.047197,0.736614,-1.936088,1.232348,-0.992640,1.572490,-1.600857,-0.939337,-1.132298,1.944400,0.960784,2.801672,-1.425010,-0.065091,-1.563766,0.235964,1.761561,-1.666007,1.753715,0.311835,-0.744844,-1.658070,0.493210,0.267064,-0.921392,1.588172,-0.749016,-1.183099,-0.762299,-1.462018,-0.364502,-0.943937,-1.308541,-0.254950,0.641254,-1.539759,0.757432,-1.206175,-1.703628,2.202868,-1.079506,-0.295042,-0.578115,-1.006985,-1.780690,-0.885142,-0.826185,-2.160086,-0.763142,-0.700725,0.309083,-1.265690,-1.042350,0.510451,-0.655041,-0.186965,-1.049635,0.031896,1.248959,-1.423514,-1.556583,1.739721,-0.269264,2.142026,-0.862284,0.447441,-0.644439,-1.732158,-1.156032,-0.789319,-0.104912,-0.654155,-0.539889,0.255346,-0.912410,-0.783327,-1.554650,-1.352737,-0.825326,0.196024,-2.253198,-0.729975,-1.167660,-0.500518,-1.410644,-0.603993,-0.090776,-0.737331,-1.123992,0.202882,2.591208,-1.469661,-1.421515,-1.829324,-0.978640,-0.397290,-1.571579,-1.338578,0.261601,-0.822915,-1.562252,1.365017,-0.699217,1.587028,0.800886,-1.657817,-1.345047,-1.244395,-0.106692,0.214961,-1.559388,-0.661952,-1.114752,0.445617,0.775664,2.477302,-1.535619,-1.419568,-0.153713,1.952555,0.592733,-1.328951,1.204201,-1.591838,0.741742,-0.833565,-0.481302,-1.208109,-0.677038,-0.909719,-1.046325,-1.294214,0.773682,-1.066107,-1.099904,-1.090959,-0.140332,0.770037,-0.921011,0.486275,-1.448793,-1.072692,-0.502131,-1.631630,-1.135291,-1.064093,-0.959927,0.819356,-2.019469,-0.912325,-1.604373,-0.461810,1.011153,-0.743730,-0.807723,1.010833,-0.892482,-1.419282,-0.814774,-0.698208,-1.699059,-1.026718,-1.180106,3.320886,-1.130451,1.264987,-0.340691,-1.016465,-0.999287,1.792526,-1.490217,1.828774,-2.104863,-1.283229,-0.155385,0.198322,-1.172674,-0.982718,-0.665887,-1.770128,-0.942152,2.400346,-0.150957,-0.724653,-2.125347,-0.681386,-1.396747,-1.097102,-1.769713,-0.574387,-0.454061,-2.147216,-0.316659,-1.052382,0.644897,-1.061383,-0.642646,-1.400374,-0.519467,-1.246131,-0.679319,0.388444,-0.338002,-0.684881,-0.349818,0.929009,-0.145259,-0.905441,-1.765781,-1.708565,-1.358742,-1.423835,1.363650,-0.460319,-0.140122,-0.796972,-0.978118,0.898613,-0.196204,-1.433949,0.999530,-1.203916,0.870776,-0.791842,-0.978386,-0.737314,-0.501904,-0.937617,-0.758737,-1.748297,-0.629054,-0.467998,0.518557,-1.428904,-0.667583,-0.444266,-1.210783,-1.220381,1.008607,-0.864255,3.524229,3.052847,-1.845801,-0.887706,-0.929267,-0.756961,-0.908989,-0.922537,-1.636314,-0.984111,-1.492465,-0.693555,1.510995,-1.553841,-0.600044,-0.702987,0.688319,0.989965,-0.838255,0.640520,0.595314,2.741295,-1.646524,-1.136899,-1.166002,-1.228386,-1.586064,-0.389605,-1.309085,0.536709,1.701359,2.110161,1.320959,-0.739241,-0.869236,-1.753166,0.417517,0.035178,-2.342409,1.838629,-0.185521,0.041729,1.840430,-1.096759,-2.025670,-1.443367,-0.763915,-0.739621,1.270057,0.627219,-1.339481,-0.538780,-0.416083,-1.716633,-0.606948,3.397716,-1.097705,-0.359204,-0.039836,1.193866,1.159737,0.501170,0.240274,-0.331963,0.217097,0.253522,2.473809,-1.568185,-0.335407,-0.884404,-0.056414,-0.635081,-1.920334,0.707683,0.871730,0.005310,-0.501229,-0.687421,-1.664472,0.500593,-1.187732,-1.820446,1.134912,-0.581686,1.508430,0.724800,-0.617667,-1.424419,0.375896,-1.482643,0.032200,0.960383,-1.186980,0.064696,-0.877007,0.370253,-0.456318,-0.125635,-0.513751,0.572974,-1.061301,-1.031744,0.851301,-0.229639,1.085585,2.929846,-0.849500,-1.268707,1.752653,0.689131,-1.187358,-1.143030,-1.983257,1.797217,-2.084896,1.942738,-1.764326,-0.873001,-1.318560,-0.323473,0.822375,-0.510951,-1.269535,-1.042989,-0.618744,-2.015139,0.329752,2.477380,0.215543,-0.481338,-0.726695,-0.179510,4.816164,-0.911092,-0.003954,1.550542,-0.580813,-0.401270,-0.995387,-0.696873,-0.390204,-1.333801,0.017671,-0.794224,-0.438683,-0.768607,-0.044039,-0.825511,2.830739,-0.572645,1.158053,-0.536175,0.580592,-0.478542,3.158906,-1.647457,-1.110784,-1.572500,-0.968537,1.243568,2.668300,-0.062622,-1.035191,-1.684281,2.565657,-0.923248,0.566332,-1.668178,0.439622,-0.513804,-2.006118,-1.358183,-0.835288,-1.412624,-1.280232,-1.105810,-0.842838,-1.096097,-0.466275,-0.457758,1.939795,-1.487939,0.468274,-0.329163,-0.185136,-0.170851,-0.473032,-0.046667,0.091717,-0.105295,-1.121182,-0.959223,-0.567524,-1.853998,-0.589226,0.120804,1.019235,-1.106960,-1.060185,-1.783667,-0.466144,-0.152751,-0.788774,0.041954,-1.103736,0.847796,-1.253847,-0.719241,-0.880311,-1.190418,-2.861133,0.956092,-0.649981,0.509703,-0.395402,-1.445885,-1.983111,1.452640,-0.965219,3.411610,-0.537568,0.636939,-1.166549,-0.666844,-0.228380,-0.664018,-0.423624,-2.101275,0.375955,-0.500474,-1.192562,-0.514548,2.746418,0.873946,-1.375701,-0.862712,0.272794,-0.801405,0.518275,1.762476,0.167840,-0.091992,-0.330543,0.668759,-0.832150,-0.624645,3.130606,-0.080795,-0.349210,-0.128785,-0.634869,-0.853644,-2.545830,1.736593,-0.581359,0.214774,0.484080,1.909346,1.351153,-1.116960,-0.924250,-0.936005,-0.432409,-1.324088,-0.992735,-1.100332,-1.471066,-0.443801,-1.572911,-0.982386,-0.421500,1.549796,-0.396078,2.109424,-1.650861,0.815614,-0.785124,-0.684110,-0.988923,-1.753772,0.568580,1.850282,-0.196403,2.947639,2.087989,0.969201,-0.709090,0.934438,0.106951,-0.779822,0.162214,-0.541358,-1.709216,-0.559579,-2.329507,0.112630,-0.636032,-2.039268,2.093140,-0.719669,-0.928032,0.557725,0.550448,-0.997263,-0.791288,-0.622261,0.084394,-0.224936,-1.244801,-0.932681,-0.884992,-0.894504,-1.303065,-1.706803,-0.588714,0.640644,-0.861977,-1.284200,-0.688694,-0.076415,-1.117034,-1.171909,0.297023,1.098006,1.628083,2.282277,-0.474251,-0.825362,-0.185283,0.504718,-1.405905,-2.436532,-2.998767,-0.379662,1.134507,-0.720056,-0.775256,-0.628536,0.503897,0.723818,-3.619493,-1.257845,-0.484262,-1.103379,0.776468,0.646981,0.305672,-1.308497,0.331600,-1.394205,-0.222404,-1.081135,0.127997,1.107268,-1.253381,1.256138,-0.815812,-0.381847,0.290058,-1.330477,0.089122,-2.569951,-0.411073,2.056709,-0.600299,-1.020068,3.009812,-0.528499,-0.446655,-0.963054,-0.157444,-0.605553,-0.323275,0.576642,0.166738,-1.139542,0.601257,-0.894995,-0.942911,-1.294685,0.083882,0.382993,-0.433813,1.060974,-0.785276,-0.128639,-0.786948,-1.195439,-0.374308,-1.061085,-1.064970,2.669633,0.295853,-0.866974,-0.580213,2.243568,-0.093448,-0.918072,0.735275,-0.741581,-0.739945,-0.356046,-0.580752,-1.826240,0.604118,-1.606404,1.529044,-1.711818,-1.546835,0.001687,-0.701944,-1.172244,0.667213,-0.913550,-2.534528,0.611179,-1.501424,-0.643780,1.281179,0.569255,1.399376,0.599204,-1.496924,-0.676352,2.377855,1.009237,-0.095733,-1.081734,-2.549558,-1.124591,1.417620,2.975915,2.789287,0.618015,-2.343363,1.917911,-1.057785,-0.667807,-1.380343,1.895958,-1.651488,-1.611225,-1.252037,1.994021,-1.027456,0.994591,-1.333285,0.531335,0.870939,-0.753906,-0.797715,0.120805,-1.659765,-0.760481,-1.365206,-0.919504,0.715430,-0.850051,1.042258,-0.933735,-1.033101,-0.147302,-1.060310,0.016336,-1.252640,1.060485,-1.003217,-0.364064,-1.214592,-1.400250,1.563183,-0.806481,-0.032876,-0.911966,-1.062509,-0.322833,1.063724,0.961357,-1.262382,-0.610530,-1.247571,-1.536295,0.642504,-1.654869,-0.724728,1.584003,0.283775,0.600247,1.785291,-1.147736,0.176081,0.141360,-1.051528,0.051448,2.089134,-0.989230,-0.929789,-0.844494,-0.106392,-1.047336,-1.175176,-1.003563,0.358862,2.206975,0.088607,3.324560,-1.518193,-1.352453,-0.931055,-0.858245,-1.662530,-0.454421,0.042661,-0.773997,0.079721,1.358968,-1.029580,-1.509559,0.262066,0.429702,0.602764,-0.545376,-0.270761,0.617859,-1.304359,-0.931717,-2.113434,-0.647754,1.020177,0.516172,-0.537794,-1.177487,0.830254,0.760554,-1.008855,0.322123,-0.849523,0.039388,1.117958,0.916219,1.161637,0.247744,-2.147872,1.387906,-0.339975,-2.439131,1.077322,-0.065659,-0.704263,-1.835461,1.898193,-0.357302,-1.067658,-0.466354,2.266375,1.370898,1.280652,-0.408979,-1.966154,-1.460079,-0.805059,-0.786172,-1.400184,1.237647,-0.123422,1.322552,-0.730211,-1.387056,1.634356,-0.473381,1.461678,0.104601,-1.087616,1.886795,-0.535671,-1.321076,1.250570,-1.110624,1.342747,-0.577775,-0.681287,-0.564266,-1.041788,-1.224548,0.020871,-0.970227,4.188709,0.545404,1.383621,-0.912514,-1.693783,-0.903360,-0.814660,-0.454048,-0.728844,-0.901359,1.895830,0.001956,2.474492,2.161302,-0.723436,-0.468998,-2.343142,-1.890028,-0.694045,-0.636759,1.438741,0.044335,-0.349606,-1.435822,-1.735417,-0.794021,-1.264678,0.017623,-0.376465,-0.156996,-1.677558,0.755875,-0.896345,-1.145785,-1.045020,-0.750034,0.605785,-0.677875,0.712971,-1.306676,-0.660528,-0.930134,-0.595050,-2.015865,-0.488982,-1.643674,0.092596,-0.686801,-0.354782,-1.043016,-1.853115,-1.938737,1.450762,-0.829554,-1.204262,-0.388754,-0.925730,-1.151479,-0.384778,-0.428460,0.546795,-0.409855,-0.038974,-0.878820,-0.603977,0.308585,-1.469265,1.213696,-0.636640,-0.570506,0.933956,1.314476,0.412114,-1.229117,-0.694794,-0.516527,1.162192,-0.706760,-1.400551,-0.359026,2.318919,-0.472957,-1.366907,2.129722,-0.537964,0.616942,-0.559646,-0.618627,0.595081,-2.083743,-0.967705,-0.767365,0.432213,-0.595839,-0.985304,-0.439572,0.378858,-0.360170,-0.771710,-0.572107,-0.338423,-0.071083,-1.351971,-1.440747,0.485849,-0.584801,-1.125141,1.298188,-0.914367,-0.478033,-1.238102,-1.325831,2.867507,-1.166914,-0.241019,-0.953936,-1.375215,0.449398,-0.794463,-1.251228,-0.438761,3.856667,0.503338,-1.947377,-0.496517,-1.761831,-0.580847,-2.162007,-1.559136,-0.152095,0.105586,2.048380,-1.043650,-0.056282,0,2306.0

##Check missing values

In [155]:
# ============================================================
# MULTIMODAL QUALITY CONTROL
# ============================================================

print("=" * 70)
print("MULTIMODAL QUALITY CONTROL")
print("=" * 70)

print("Patients:")
print(multimodal["patient_id"].nunique())

print()

print("Duplicate patients:")
print(multimodal["patient_id"].duplicated().sum())

print()

print("Missing values per column:")

missing = (
    multimodal
    .isna()
    .sum()
)

display(
    missing[
        missing > 0
    ]
    .sort_values(ascending=False)
)

======================================================================
MULTIMODAL QUALITY CONTROL
======================================================================
Patients:
357

Duplicate patients:
12

Missing values per column:

Series([], dtype: int64)

##Remove duplicate patients

In [156]:
# ============================================================
# REMOVE DUPLICATE PATIENTS
# ============================================================

print("=" * 70)
print("REMOVING DUPLICATE PATIENTS")
print("=" * 70)

print("Before:")
print(multimodal.shape)

multimodal = (
    multimodal
    .sort_values("file_uuid")
    .drop_duplicates(
        subset="patient_id",
        keep="first"
    )
    .reset_index(drop=True)
)

print("\nAfter:")
print(multimodal.shape)

print("\nUnique patients:")
print(multimodal["patient_id"].nunique())

======================================================================
REMOVING DUPLICATE PATIENTS
======================================================================
Before:
(369, 1024)

After:
(357, 1024)

Unique patients:
357

##Event distribution

In [157]:
# ============================================================
# EVENT DISTRIBUTION
# ============================================================

print("=" * 70)
print("SURVIVAL LABELS")
print("=" * 70)

print(multimodal["event"].value_counts())

print()

print("Event ratio:")

print(
    multimodal["event"].mean()
)

======================================================================
SURVIVAL LABELS
======================================================================
event
0    266
1     91
Name: count, dtype: int64

Event ratio:
0.2549019607843137

##Save the master dataset

In [158]:
# ============================================================
# SAVE MASTER DATASET
# ============================================================

master_path = os.path.join(
    SAVE_DIR,
    "multimodal_master_dataset.csv"
)

multimodal.to_csv(
    master_path,
    index=False
)

print("=" * 70)
print("MASTER DATASET SAVED")
print("=" * 70)

print(master_path)

======================================================================
MASTER DATASET SAVED
======================================================================
/content/drive/MyDrive/TCGA_BRCA/multimodal_dataset/multimodal_master_dataset.csv

##TESTING

##Reload the saved dataset

In [159]:
# ============================================================
# LOAD FINAL MASTER DATASET
# ============================================================

master_path = os.path.join(
    SAVE_DIR,
    "multimodal_master_dataset.csv"
)

master = pd.read_csv(master_path)

print("=" * 70)
print("FINAL MASTER DATASET")
print("=" * 70)

print(master.shape)

display(master.head())

======================================================================
FINAL MASTER DATASET
======================================================================
(357, 1024)

,patient_id,file_uuid,years_to_birth,Tumor_purity,pathologic_stage,pathology_T_stage,pathology_N_stage,pathology_M_stage,number_of_lymph_nodes,radiation_therapy,histological_type_infiltratinglobularcarcinoma,histological_type_medullarycarcinoma,histological_type_metaplasticcarcinoma,histological_type_mixedhistology(pleasespecify),histological_type_mucinouscarcinoma,"histological_type_other,specify",PAM50_Her2,PAM50_LumA,PAM50_LumB,race_blackorafricanamerican,race_white,ethnicity_nothispanicorlatino,CLEC3A,CPB1,SCGB2A2,SCGB1D2,TFF1,GSTM1,PIP,S100A7,MUCL1,CYP2B7P1,ANKRD30A,PRAME,CYP4Z1,KCNJ3,AGR3,HMGCS2,SERPINA6,TFAP2B,MUC6,DHRS2,SLC30A8,UGT2B11,VSTM2A,COL2A1,C4orf7,TAT,ADIPOQ,ADH1B,CALML5,GP2,MYBPC1,GABRP,KRT14,CEACAM5,MUC5B,TFF3,C1orf64,SOX10,GRIA2,KRT5,CRABP1,GSTT1,SYT13,STAC2,CST9,LTF,KRT6B,BMPR1B,KLK11,HOXB13,CYP2A6,FABP7,NPY1R,CEACAM6,GFRA1,CRISP3,ABCC11,C20orf114,CLCA2,KIF1A,PVALB,LRP2,TCN1,AGR2,OBP2B,CP,CGA,PGR,KCNC2,SLC34A2,OLFM4,KRT6A,KLK5,MUC16,CYP4F8,PROM1,BPIL1,KRT16,DSG3,FAM5C,MSLN,SLC5A8,A2ML1,CBLN2,SERPINA11,NLRP2,PIGR,PTPRT,AQP5,KRT81,ELF5,KRT17,CA9,VGLL1,BEX1,CST1,TUSC5,SLC6A4,LBP,KLK6,KLK10,CYP4Z2P,PPP1R1B,NXPH1,SLITRK6,KLHDC7A,LRRC31,ESR1,C10orf82,PPP2R2C,EEF1A2,SYT9,DCD,ANKRD30B,SCGB2A1,ORM1,CALML3,GRPR,FABP4,CHAD,TNNT1,CST5,SORCS1,MAGEA6,KLK7,ASCL1,MUC2,CLIC6,PDZK1,CDC20B,CXCL17,SLC6A14,RPS28,PEG10,DIO1,CARTPT,FOXI1,NBPF4,SPAG6,PYDC1,C7,SDR16C5,CASP14,CNTNAP2,ABCC8,WNK4,MUC15,CIDEC,LCN2,S100A7A,PPAN-P2RY11,SCUBE2,MIA,S100A8,ABCA12,SCGB3A1,PGLYRP2,FOLR1,DSC3,C2orf54,CAPN8,IGSF1,MSMB,CXCL13,S100A9,LRP1B,MAGEA3,SERPINA5,TMPRSS4,LY6D,TRH,SERPINB5,GLYATL2,SLC7A4,HS6ST3,SLC5A1,PON3,MMP1,ERBB4,SLC44A4,SFRP1,NBPF6,PLA2G2A,COL17A1,ALB,ZIC1,S100P,ROBO2,RIMS4,ORM2,CYP4F22,WIF1,NEK10,NCRNA00052,GLRA3,TMC5,ABCC13,IL20,ROPN1,PI16,LPPR3,ELOVL2,INSM1,TSPAN8,CCL19,SLC9A2,SLC7A2,LEP,PI3,LOC728606,FREM2,MS4A15,WFDC2,KNDC1,FAM3B,HGD,ATP6V0A4,WDR72,FGB,CAPN6,CHST8,ATP13A5,NKAIN1,TRPA1,SYT1,NCCRP1,FAM5B,PTPRZ1,ANXA8,CYP4B1,HORMAD1,VTCN1,FOXJ1,CCL21,SYTL5,KLK8,ACTL8,PKP1,CR2,GRB14,SPDYC,KRT15,PLIN1,AGTR1,CHGB,BCAS1,C16orf89,GLDC,TPRG1,BBOX1,TMPRSS6,GPD1,HOTAIR,CYP4X1,TUBA3D,ART3,SYT8,LRG1,GPR98,NAT1,CYP2A7,MS4A1,FSIP1,FAM196A,CIDEA,GSTA1,TRIM29,SLPI,PROL1,NDP,DLK1,CHIT1,ZIC2,FLJ45983,PAX7,ROPN1B,SOSTDC1,HEPACAM2,PPP4R4,PCSK1N,ALOX15B,PNMT,ATRNL1,IGDCC3,CST4,TF,MARCO,PSCA,MMP12,RGS22,ANXA8L2,DSG1,C2CD4A,SLC13A2,LOC100271831,GPR26,AKR7A3,ONECUT2,GABRB3,HOXC11,PRODH,GJB1,KRT23,KRT6C,RBM24,C1orf173,C19orf33,C3orf57,GRIK3,FOXA1,TRPV6,THRSP,UGT2B15,ARHGAP36,DARC,SAA2,SHISA9,KRT4,TMPRSS3,FUT3,VSIG2,IGJ,POF1B,PPP1R14C,SAA1,VIPR2,TPSG1,PRSS21,TDRD1,HBA1,PLIN4,TFPI2,KRT13,AREG,TTYH1,SLC26A3,SLC28A3,PLCH1,MMP13,CCNO,AR,DLX2,DKK1,CXADRP3,SYNPO2L,AFF3,ATP13A4,S100A2,AKR1B10,PI15,SPAG17,NTNG1,FAM83E,SBSN,PCDHA11,ANKRD43,ZNF385B,NPY5R,F7,HSD17B2,DCX,NELL2,MAPK4,FGG,PCDHA12,IYD,SOX2,MYT1,CACNG4,DCDC2,FAM83A,EPYC,ADCY5,TSIX,CHI3L2,PHGR1,PCDH10,WT1,SHISA2,KCNG1,PP14571,EDN3,HPX,RIMS2,COL11A1,CD177,TLX1,PCK1,GLYATL1,CYP4F11,SEZ6L,LOC642587,S100A1,TTC36,MMP7,PART1,NEURL,TBC1D3G,CNTFR,GABBR2,CRYM,TOX3,PPP1R1A,SCRG1,PLA2G2D,LGR6,RET,SLC15A1,ZFP57,SMOC1,HOXC10,TUBA3E,UGT2B28,MKRN3,HRASLS5,SLC6A11,CXCL14,CHGA,PLA2G3,KCNF1,RHCG,CHRDL1,TSPAN1,MKX,BCL11A,FBN3,MS4A8B,SLC6A15,NKX2-2,MAGEA1,FUT6,MAPT,CTNND2,CPLX2,AKR1C2,DOK7,UGT8,PCSK1,LOC389033,CECR2,APOD,OGN,RASAL1,DACH1,ABCC12,HP,TMEM40,MMP10,CPA6,ABCA8,FAT2,SCNN1G,DEFB1,LY6K,C2orf40,SCARA5,FGFBP1,NOVA1,CLGN,FGF10,SCGN,PIK3C2G,CCL18,RBP4,GRM4,TPSD1,ADAMTS15,CD79A,C1orf106,TNFSF12-TNFSF13,FLT3,AQP7,PAH,GPRIN2,PLIN5,NMU,IRX4,ADAMTS19,SHC4,CLSTN2,GATA4,GJB3,B3GNT3,FCRL5,TMEM132C,SLC1A1,EMX1,PCOLCE2,DLGAP1,PSAT1,MAOB,COL9A3,AFP,ADAM6,LOC339535,IRX1,LOC440905,SEMA3E,CD300LG,SERHL2,GNG4,CAPN9,MYO3B,LOC84740,PDZK1IP1,SLC44A5,CXorf61,DNALI1,HAPLN1,PAX2,SLC19A3,CD19,DLX1,SPDEF,C6,SERPINB2,MAGEA4,IL12RB2,UNC5A,CAPN13,CHRM1,COCH,PEG3,CKMT1A,TMEM213,FERMT1,SPINK8,SOX11,NELL1,PADI3,TNNI3,CXCL9,CHI3L1,PCDHA10,PTCHD1,FUT9,CA8,LOC145837,LRRC26,GAL,CWH43,CA12,DNER,RNF183,L1CAM,SLC27A6,STC2,DPYSL5,CDSN,ACTA1,TRIM58,PCDHA6,MAGEA2,TMEM45B,UBD,ADAMTS16,GATA5,FAM184B,DEGS2,PRG4,ANO5,C2orf72,HHIPL2,HPGD,FIBCD1,KRT7,C2orf82,PCDHA4,ALOX15,VWDE,EN1,DES,KCNK15,ACTG2,TP63,ST8SIA6,NTS,IGFALS,ZBTB16,LGALS12,ABCA13,C1orf168,B3GALT5,IDO1,CXCR2P1,GPX2,GPR110,DBC1,PTPN20B,EREG,KRT75,GRIA1,SPIB,NTRK3,SCUBE1,SAMD11,C1orf95,S100B,NKX2-5,TMEM150C,ANO3,TCL1A,VWA2,SLC27A2,LIN7A,ACE2,RASSF10,PEBP4,NCAM2,AMY1A,MAT1A,MAPK15,ATP6V1B1,XAGE1D,VSTM2L,NLRP5,ACTN2,CDH19,FAM3D,LRTM2,C8orf85,MGAM,KCNH1,SLC12A1,RTBDN,MLPH,LOC96610,DPY19L2P4,DNAJC12,CHST9,UGT2B4,SIX3,SP5,C10orf81,OSR1,SCAND3,KLK14,LONRF2,HOXC13,GPM6A,THBS4,MT1G,MYEOV,ARX,SCEL,CYP24A1,CLDN8,UPK1A,MAGEA12,TCAM1P,CACNG6,COL4A6,GRP,RIMS1,ADAMDEC1,BRSK2,GREB1,GPR12,RP1,PLP1,DNAH11,PRR15,CPA3,KCND3,CSAG3,POU2AF1,ZMAT4,FAM135B,CST2,LOC100128977,ABHD12B,AKR1B15,FAM83B,AK5,MUM1L1,RANBP3L,FLRT3,SCNN1B,ADCY2,CACNG1,SLC30A2,AP3B2,IL6ST,CALB2,PCDHA1,FOXD1,PHYHD1,TUBB2B,TIMP4,SPESP1,PNCK,CITED1,SERPINB7,SULT4A1,SUSD3,GAD1,CADM3,SELP,PLAC2,MNX1,ATP1A2,UGT1A6,GPR158,SMC1B,ALDH3B2,IVL,CACNA1H,PHF21B,TNS4,TYRP1,C1orf116,LOC150622,ADH1C,LOC389493,C19orf21,EGF,AQP9,KLK12,CD1A,LPAR3,TMEM145,GJB5,LOC100130148,ALDH1L1,PTX3,SLITRK5,MSI1,CXCL1,XDH,SCUBE3,ADCY1,CKMT1B,KCNK3,B4GALNT2,SIX1,GJB6,EHF,WDR17,ALOX12P2,KLK13,UPF0639,CORO6,DQX1,P2RY11,C21orf15,SCN7A,BMP7,PCSK2,ENTPD8,AGT,AMBP,GREB1L,ATP1A4,SLC16A6,RELN,PRSS12,HPN,RIC3,TMEM84,MMP3,LOC153328,LY6G6C,KCNE4,SLC35F3,TBX1,FGFR4,HOXB5,KLK4,AQP3,WISP3,LOC152225,C6orf141,CXCL5,MGC29506,PCDHA13,C6orf15,PITX1,CAPSL,HRASLS,KCNK2,NPW,C14orf180,SOX8,CES3,CAMK2B,CUX2,CT62,DUSP9,EPHA8,KRT31,NXNL2,RERGL,KIAA0125,ACMSD,TDRD9,FABP6,DAPL1,ADCYAP1,CYP4F12,CFB,GSDMC,KIF12,HMP19,KCNK1,BLK,WNT6,CLEC10A,RARRES1,CSN3,PCDHGB5,ARMC3,C1orf130,KRT86,CPA4,CHRDL2,TNFRSF17,GZMB,HRCT1,ITIH5L,LRAT,C4A,FAIM2,SERPINA3,GRIA4,TDRD12,LYPD6,COMP,CD38,PTPRN2,CRTAC1,TARP,FOSB,SMYD1,SMR3B,AKR1C1,C9orf152,NME5,LGALS7B,GPT,MT1A,IL33,RNF212,PRSS16,STEAP4,TPSB2,ACOX2,CHODL,CTSG,CNTN1,C4BPA,REEP6,CILP,KISS1R,TGM3,C8orf84,OXGR1,SRPK3,ARC,PRKAA2,IBSP,ATP1A3,CAMP,STK32B,IL7R,CCL28,SLC4A10,PGC,HS6ST2,AZGP1,PYY,BAIAP3,KIAA0408,MRAP,SFTPA2,FOXA3,CRHR1,MOGAT2,GPR87,CPNE4,GFRA3,CHRNA9,CCL14,TMEM139,ODZ2,SLIT1,NPY2R,ITGB6,GLB1L2,SPINK5,HMGCLL1,SNORD116-4,FGFR3,CRISPLD1,SPRR3,ABP1,LMO3,GZMK,LRRN1,RUNDC3A,LGALS7,ALG1L,EYA1,CD36,ACCN1,GGT6,ABCA4,IGSF21,BARX1,BPI,KLRG2,FAM189A1,PXDNL,ECEL1,FCER2,OGDHL,GABRE,TNN,PLEKHG4B,IL20RA,MUC13,SDK2,LTB,TNNT3,GNG13,LACRT,SYT5,C6orf223,KIAA0319,KLHDC7B,MESP1,MUC7,LEFTY2,KCNH2,CYP26A1,PCDH20,COL22A1,CST6,PCDHGB1,NRK,ZMYND10,FMO2,GDF15,CYP21A2,LAMC2,MAG,NRXN1,GRAMD2,PRSS33,FCRL3,PCP4L1,MAP7D2,LGR5,FXYD1,CES1,CDH7,VIT,PNPLA3,LEMD1,DPP10,HDC,IL6,CACNA2D1,ZPLD1,CCDC129,LDHC,LOC284379,KLHL1,C20orf85,CHRNB2,MMRN1,EDIL3,PEX5L,MLC1,psiTPTE22,BMP5,MAGEC2,CXCL11,PLA2G10,TGM5,CD207,COL11A2,SNAP25,CDCA7,CLDN10,OBP2A,ENHO,EPHA7,B3GAT1,COL10A1,CRLF1,DNAH5,DMKN,SLC1A6,PTGDS,TFCP2L1,ZIC5,CRYAB,EMILIN3,TNNT2,INA,event,survival_time
0,TCGA-AC-A3BB,00ab866f-a0a3-44c0-ad14-c9dc833239a7,-0.962155,-1.473020,3,3,2,0,0.663363,1,True,False,False,False,False,False,False,True,False,True,False,True,1.131186,-0.217377,-0.721849,-0.573624,0.767786,1.468423,0.753273,-0.037026,0.102156,1.058665,0.600341,-0.520988,0.597260,0.825032,0.497562,0.984730,-0.712401,0.962603,0.254556,0.497343,0.212075,-0.637925,-0.042129,-0.974846,0.755011,1.628470,1.496313,1.517788,0.372917,1.177870,1.267334,-0.236729,0.208027,-0.669385,0.623399,0.411118,0.530921,0.106309,0.876753,-0.078121,-0.675873,-1.851147,-1.044138,0.183039,-0.525735,0.823604,-0.155413,-1.001285,1.410797,-0.786591,0.217726,-0.205545,0.002333,-0.321268,0.784344,-1.135516,0.534683,0.517773,0.058905,-0.558987,0.612891,0.168261,1.908895,0.514928,0.026689,-0.550162,-0.749016,0.644418,-0.323037,-0.595068,-0.110948,-0.985101,-0.303672,0.471297,2.766400,0.468403,0.684100,0.028341,0.003189,0.955315,0.219589,-0.860445,-0.890179,-0.575318,0.935241,-0.488691,0.043624,0.700257,-0.782802,-0.085072,0.024198,-0.072386,-0.717198,-0.388216,-0.351786,-0.898367,1.820741,-0.452732,0.807845,-0.421646,0.731859,0.763437,0.716471,1.621300,0.106702,-0.032482,1.147030,-0.117872,0.977256,-0.872248,0.522265,1.423529,-0.539889,0.622987,-0.588484,-0.340971,0.553448,1.098529,1.528816,0.605691,0.548763,2.834333,-0.176739,-0.500518,-0.212787,-0.775843,-0.637921,-0.538638,1.596861,-0.156308,0.538781,-0.389665,1.142437,-0.195456,-1.274406,-0.39729,0.887777,-0.633855,-0.777064,0.817034,1.689882,-0.006899,-0.552563,-1.189244,0.978802,0.616220,-0.585472,1.852674,-0.194465,-0.639082,-1.559388,0.043516,-0.078982,-0.521650,-1.798421,1.638891,1.059877,-0.267134,-0.129433,0.607718,1.161639,0.590136,-0.849255,0.823983,-0.378167,-0.504500,-0.481302,0.449801,-0.045246,-0.471887,-0.164191,-0.022286,-0.997681,0.513985,0.500419,-0.140861,-0.041096,-0.487469,0.319494,0.267989,0.499949,-0.711129,1.552805,0.345904,1.492129,1.444327,-0.135230,-0.265723,0.351711,0.478683,2.130067,-0.372361,1.485519,-0.228294,1.403015,0.808825,-0.620442,1.177843,-0.320544,0.769461,-0.074531,-0.430211,0.479622,-0.031205,1.389338,-0.572230,0.195767,1.821973,-0.629236,0.076543,-0.830821,1.189094,1.068866,0.556100,-1.497685,1.241667,0.357706,-0.798085,-0.665887,0.206764,1.741585,-0.817324,-0.127124,-0.798055,0.627041,0.518156,-0.867860,-0.429066,-0.415726,0.867227,-0.485925,0.585154,-0.702344,1.024114,0.859925,-0.529941,-0.594182,-0.222538,0.998378,-0.341163,-0.679319,-0.190806,1.877764,0.053373,0.273456,-0.011868,0.259112,-0.722437,0.958823,-0.158405,0.018679,1.885333,1.116292,0.066421,1.862427,-0.330782,0.394455,0.793706,0.345649,1.029704,0.987399,1.253195,0.771956,-0.618744,2.072309,-0.931645,-0.164996,0.285873,1.148471,0.901672,-0.466716,0.621679,-0.028016,0.370340,-0.123477,-0.906357,-0.296876,0.395309,-0.083222,-0.522301,1.021740,0.862646,0.396414,1.359276,2.482427,0.419104,-0.329462,-1.054644,-0.006167,0.329744,-0.391560,-0.420640,-0.943334,0.275189,1.114078,-0.423855,0.051791,-0.625920,-0.399307,0.932773,0.113189,0.373200,-0.242450,-0.276995,1.160253,0.053014,-0.955024,-0.039660,0.455466,0.289458,-0.750483,1.082636,-0.564890,0.126152,1.571136,0.742285,0.329084,-0.335726,0.248484,-0.458931,1.112080,0.570316,0.344287,-0.678287,1.456265,1.528402,-0.280847,-0.671204,-1.014690,0.646756,1.754011,0.128259,-0.597444,0.500157,-0.486345,1.370750,0.565214,-1.678691,0.186553,0.242316,0.143127,1.419295,-0.201459,0.627806,-0.082341,0.172168,-0.301716,-0.624345,-0.419788,-0.856516,-1.057131,0.227206,-1.017789,-0.280668,0.962431,2.056501,1.077834,0.197026,1.072527,-0.726925,1.190838,1.044203,-0.454649,-0.581686,0.325280,-1.243478,0.176276,-0.385878,0.656079,0.289864,0.181337,0.201593,0.843880,1.648905,0.219487,0.575342,-0.426701,-0.033212,-0.161342,-0.387996,-0.291614,-0.017362,1.493648,-0.522244,0.219077,0.519094,-0.082315,1.661673,-0.137179,-0.477124,0.096724,0.453959,0.442928,1.552156,-0.122252,-0.744941,0.394331,1.424156,1.394652,-0.390751,0.781738,0.486264,1.281774,0.105170,1.112077,0.020369,0.614114,-0.261793,1.828618,0.280418,0.832103,2.167364,-0.644406,-0.702957,0.631885,-0.635197,0.700437,0.593420,-0.574250,-0.055286,0.086748,1.403541,0.762550,-0.492909,0.457059,-0.622847,0.508651,-0.232674,0.442614,-0.572645,-0.630424,0.816160,-0.307954,-0.300110,1.074446,0.548808,-0.528203,-0.376772,2.162384,-1.462133,0.322147,0.941635,-0.374810,0.372008,-0.652614,1.166440,-0.790754,-0.503308,-0.566134,1.347716,-0.226592,-0.957557,0.920346,-0.471819,0.543566,1.033280,-0.108660,-0.033913,1.047479,0.409527,0.070576,-0.860021,0.003382,1.736382,0.799413,-0.447887,0.865932,1.247818,-1.092228,0.347832,1.052349,1.944192,-0.645739,0.304791,0.437989,-1.081794,0.076954,-0.111805,-0.896666,0.370188,-0.502728,-0.754465,-0.020206,0.897954,1.815387,-0.653543,2.055570,1.575365,-0.849169,-0.138888,0.363646,1.134385,2.035853,0.990132,1.481854,0.190275,0.574171,0.536150,1.250794,-0.981911,-0.043195,0.898571,-0.527183,-0.298701,0.351366,0.197904,-0.423624,0.560633,-0.993116,1.365484,1.878047,1.610453,0.345419,0.477642,2.088214,-1.084367,-0.431113,0.027252,-0.091337,0.665698,-0.485805,-0.493140,-0.452836,0.238606,-1.054904,-0.620858,-0.527378,-0.594593,-0.245014,-0.227845,0.717297,0.806684,0.254285,0.315853,-0.673395,0.938367,-0.476087,0.786924,1.114137,0.857569,0.858203,0.478719,-0.513043,1.601716,-0.602323,-0.473144,0.975056,-0.338630,0.838603,0.906596,1.161892,1.280660,-0.396078,0.213761,0.389786,1.125276,-0.240561,0.123064,0.917499,1.126782,-0.492633,-1.199415,-1.598149,-0.138468,0.252419,0.613213,-0.001473,1.127133,1.020922,-0.156639,0.036751,1.053415,1.456052,-0.320709,-0.015489,0.426989,-0.446707,1.401355,1.050710,1.679691,-0.593572,1.413372,0.052802,0.652198,0.273420,-0.907480,-0.722232,0.084857,0.743870,-1.160998,-0.884992,-0.183536,1.533966,0.474207,0.268293,0.364489,0.251926,1.142897,-0.235158,0.656004,-0.042133,1.276654,0.725060,-0.020602,0.853537,-0.437801,-0.305552,0.275790,0.111926,-0.225436,-0.520116,-0.375182,-0.035226,-0.379662,0.018841,1.253895,0.300730,-0.628536,-0.982226,-0.780450,0.363733,1.953731,0.425777,0.235556,-0.316767,0.627135,0.824855,-0.222793,0.783947,-0.945726,-0.622442,-0.293400,0.418539,0.867587,0.909235,0.282866,-0.091990,0.614598,0.615198,0.337954,0.086303,-1.082493,-0.668447,-0.479767,-0.406639,0.213788,0.425855,1.158612,-0.446655,-0.314908,2.521693,1.038932,1.100508,-0.751030,0.396072,-0.320051,1.041028,-0.552842,-0.624628,0.454933,-1.052783,0.642629,0.887540,0.303607,-0.590686,0.991321,-0.411895,-0.572081,0.219698,2.019716,1.642267,-0.408602,-0.731391,1.405301,0.257045,1.162296,-0.040539,-0.735379,0.328549,0.778486,-1.140981,1.103019,-0.420877,1.095101,1.581984,-0.141943,0.885840,-0.258917,1.553387,0.828950,-1.014666,0.925934,-0.548094,-0.348355,1.245670,0.107258,1.835476,1.426458,-0.073837,0.184704,1.706069,-0.563203,-0.135129,-0.959322,-0.736089,-0.560741,-0.045058,-0.053155,-0.543914,-0.095226,0.605258,1.317953,1.328485,1.523519,0.094966,-0.800162,0.514050,0.980505,-0.258349,-0.802981,-0.081431,-0.280856,1.383405,1.923519,0.501280,-0.796937,-0.624551,0.182331,0.592295,-1.107357,1.026803,-0.144154,0.455439,-1.000758,0.098028,-0.719459,0.158813,-0.443773,-1.039356,0.811384,-0.916631,1.139962,-0.731825,0.989873,0.942528,-0.041267,0.193856,-0.605165,-0.163127,0.992490,0.034834,-0.813466,0.848080,-0.216129,0.686280,-0.057313,0.795061,0.631948,1.172568,-0.019786,-0.361782,0.710928,0.147238,-0.613806,-0.005720,-0.408204,0.101361,0.719926,0.038634,-0.563135,0.602287,-0.632599,-0.465902,0.718345,0.899843,-0.632843,0.931821,-0.907696,-0.114616,0.139164,-0.346769,2.419527,0.165242,-0.058235,-0.433657,0.763590,0.202972,-0.345366,-0.071854,-0.268682,0.897623,1.344395,1.082240,1.362659,-0.020495,0.880354,-0.670528,1.018145,1.050058,0.488431,-0.544439,0.702669,-0.037870,0.000876,1.734976,0.371860,1.691333,0.207242,-0.369611,0.317962,0.153664,0.192774,0.046106,0.527985,-0.241417,0.972168,0.868180,0.187642,0.017248,-0.759257,0.750757,-0.308031,0.943788,0.452882,-0.765648,0.267028,0.762711,0.819436,0.539186,-0.255569,0.517273,1.480519,-0.705388,-0.260827,1.481514,0.304787,0.600514,0.323944,0.373329,0.895243,1.165937,0.685219,0.568069,0.778985,1.254997,0.527463,-0.444159,1.431755,0.336931,0.615558,0.881307,1.329038,-0.312809,-0.909377,-0.561124,-0.828907,0.048887,0.009306,-0.235844,-0.542652,0.249741,1.003498,0.632116,0.650025,0.509740,0.154834,-0.096645,0.234114,0.490549,1.197702,-0.453251,1.574147,2.310554,-0.436041,-0.557746,0.202210,1.090717,-0.604724,-0.788647,-1.107635,-0.723436,1.655359,-0.728768,-0.485033,-0.358762,-0.139470,-0.113797,-0.070061,-0.937588,0.151627,-0.378172,-0.355086,-0.171109,-0.560776,0.725966,-0.116448,1.072509,0.967345,-0.737734,-0.162885,-0.022102,0.165216,1.536296,1.777328,0.448433,1.236854,0.301848,0.835292,-0.637332,-0.698954,1.274027,-0.886015,0.288528,1.608255,-0.269199,0.483235,0.777025,-0.424050,-1.005648,-0.829554,-0.389313,1.681936,1.395357,-1.151479,-0.384778,1.175447,0.304674,-1.305136,-0.345405,1.082851,3.028321,1.666502,-0.260134,0.811453,-0.093895,0.120715,0.581974,0.588582,-0.304485,0.923494,0.724427,0.250315,0.874862,-1.139291,1.115951,-0.613688,1.122151,-0.472957,1.247280,-0.206134,-1.142285,-0.645157,1.650610,0.661351,-0.095320,-0.025363,-0.423007,-0.554351,-0.620062,0.766051,1.217838,-0.634768,0.311136,-0.949528,1.262645,-0.195910,-0.338423,-0.514648,-0.080042,1.002338,-0.369770,0.819319,0.014197,1.185987,0.027896,-0.478033,0.460518,0.559655,0.646868,0.704776,-0.027656,0.327826,-0.408933,0.053615,0.644690,0.215716,-0.434615,-0.043895,0.367797,0.358646,0.308021,1.057869,-0.365232,1.614857,-0.969645,-0.384022,0.737494,0.452037,-0.530162,0.002997,0,987.0

##Complete validation

In [160]:
# ============================================================
# FINAL MASTER DATASET VALIDATION
# ============================================================

print("=" * 70)
print("MASTER DATASET VALIDATION")
print("=" * 70)

print("Rows:")
print(len(master))

print("\nUnique patients:")
print(master["patient_id"].nunique())

print("\nDuplicate patients:")
print(master["patient_id"].duplicated().sum())

print("\nMissing patient IDs:")
print(master["patient_id"].isna().sum())

print("\nMissing survival times:")
print(master["survival_time"].isna().sum())

print("\nMissing event labels:")
print(master["event"].isna().sum())

print("\nNumber of pathology feature files:")
print(master["file_uuid"].notna().sum())

print("\nEvent distribution:")
print(master["event"].value_counts())

print("\nEvent ratio:")
print(round(master["event"].mean(), 4))

======================================================================
MASTER DATASET VALIDATION
======================================================================
Rows:
357

Unique patients:
357

Duplicate patients:
0

Missing patient IDs:
0

Missing survival times:
0

Missing event labels:
0

Number of pathology feature files:
357

Event distribution:
event
0    266
1     91
Name: count, dtype: int64

Event ratio:
0.2549

##Verify every pathology feature exists

In [161]:
# ============================================================
# VERIFY FEATURE FILES EXIST
# ============================================================

missing_files = []

for uuid in master["file_uuid"]:

    path = os.path.join(
        FEATURE_DIR,
        f"{uuid}.npy"
    )

    if not os.path.exists(path):
        missing_files.append(uuid)

print("=" * 70)
print("FEATURE FILE VALIDATION")
print("=" * 70)

print("Missing feature files:")
print(len(missing_files))

if len(missing_files) > 0:
    print(missing_files[:10])
else:
    print("All pathology feature files exist.")

======================================================================
FEATURE FILE VALIDATION
======================================================================
Missing feature files:
0
All pathology feature files exist.

##Check feature dimensions

In [162]:
# ============================================================
# VERIFY FEATURE DIMENSIONS
# ============================================================

sample_size = min(10, len(master))

dimensions = []

for uuid in master["file_uuid"].sample(sample_size, random_state=42):

    feature = np.load(
        os.path.join(FEATURE_DIR, f"{uuid}.npy")
    )

    dimensions.append(feature.shape)

print("=" * 70)
print("FEATURE DIMENSIONS")
print("=" * 70)

for shape in dimensions:
    print(shape)

======================================================================
FEATURE DIMENSIONS
======================================================================
(5733, 512)
(3073, 512)
(964, 512)
(16455, 512)
(5704, 512)
(2393, 512)
(15186, 512)
(6432, 512)
(2471, 512)
(17117, 512)

##Summary report

In [163]:
# ============================================================
# FINAL SUMMARY
# ============================================================

print("=" * 70)
print("MULTIMODAL DATASET SUMMARY")
print("=" * 70)

print(f"Patients               : {len(master)}")
print(f"Clinical features      : {clinical.shape[1]-1}")
print(f"Genomic features       : {genomic.shape[1]-1}")
print(f"Survival labels        : Yes")
print(f"Histopathology slides  : {master['file_uuid'].notna().sum()}")
print(f"Recurrence events      : {master['event'].sum()}")
print(f"Non-recurrence         : {(master['event']==0).sum()}")
print(f"Event ratio            : {master['event'].mean():.3f}")

print("\nDataset is ready for model development.")

======================================================================
MULTIMODAL DATASET SUMMARY
======================================================================
Patients               : 357
Clinical features      : 20
Genomic features       : 1000
Survival labels        : Yes
Histopathology slides  : 357
Recurrence events      : 91
Non-recurrence         : 266
Event ratio            : 0.255

Dataset is ready for model development.