# Dataset Splitting Pipeline

## Overview

This notebook performs dataset splitting for a multimodal breast cancer Recurrence-Free Survival (RFS) prediction dataset.

The objective is to divide the constructed multimodal dataset into independent training, validation, and testing subsets while preserving the distribution of RFS recurrence events across all splits.

A fixed random seed is used to ensure reproducibility.

---

## Dataset Splitting Strategy

The complete multimodal dataset is divided into three subsets:

- Training set: 70%
- Validation set: 15%
- Testing set: 15%

The splitting process uses stratified sampling based on the RFS event variable to maintain similar recurrence-event distributions across all subsets.

Random seed:

- 42

---

## Pipeline

1. Load the final multimodal RFS dataset.

2. Initialize random seed for reproducibility.

3. Perform stratified train-validation-test splitting:

   - Training dataset (70%)
   - Validation dataset (15%)
   - Testing dataset (15%)

4. Verify dataset distributions:

   - Number of patients
   - Number of recurrence events
   - Event ratio
   - Patient distribution across subsets

5. Export split datasets:

   - train_rfs.csv
   - validation_rfs.csv
   - test_rfs.csv

6. Save patient ID lists for each split:

   - train_rfs_patient_ids.csv
   - validation_rfs_patient_ids.csv
   - test_rfs_patient_ids.csv

---

## Dataset Split Results

The final multimodal dataset contains:

Total patients:

- 357 patients


Dataset distribution:

| Split | Patients | Percentage |
|------|----------|------------|
| Training | 249 | 70% |
| Validation | 54 | 15% |
| Testing | 54 | 15% |


RFS outcome distribution:

- Total recurrence events: 91
- Censored cases: 266

---

## Quality Control and Validation

The generated splits were verified to ensure:

- No duplicated patients
- No patient overlap between subsets
- Consistent dataset structure
- Preserved RFS event distribution
- Reproducible splitting using random seed 42

---

## Output

The generated datasets are stored in:

dataset_split_rfs/


The resulting datasets are ready for:

- Genomic feature selection
- Multimodal survival model development
- Transformer-based RFS prediction
- Classical survival model comparison

##Imports

In [ ]:
# ============================================================
# IMPORTS
# ============================================================

import os
import random

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

print("Libraries loaded successfully.")

Libraries loaded successfully.

##Mount Google Drive

In [ ]:
# ============================================================
# MOUNT GOOGLE DRIVE
# ============================================================

from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

##Project Paths

In [ ]:
# ============================================================
# PROJECT PATHS
# ============================================================

BASE_DIR = "/content/drive/MyDrive/TCGA_BRCA"

MASTER_DATASET = os.path.join(
    BASE_DIR,
    "multimodal_rfs_dataset",
    "multimodal_master_RFS_dataset.csv"
)

SAVE_DIR = os.path.join(
    BASE_DIR,
    "dataset_split_rfs"
)

os.makedirs(
    SAVE_DIR,
    exist_ok=True
)

print("="*70)
print("PROJECT PATHS")
print("="*70)

print("Master dataset:")
print(MASTER_DATASET)

print("\nOutput folder:")
print(SAVE_DIR)

======================================================================
PROJECT PATHS
======================================================================
Master dataset:
/content/drive/MyDrive/TCGA_BRCA/multimodal_rfs_dataset/multimodal_master_RFS_dataset.csv

Output folder:
/content/drive/MyDrive/TCGA_BRCA/dataset_split_rfs

##Load Master Dataset

In [ ]:
# ============================================================
# LOAD MASTER DATASET
# ============================================================

multimodal = pd.read_csv(
    MASTER_DATASET
)

print("="*70)
print("MASTER DATASET")
print("="*70)

print("Shape:")
print(multimodal.shape)

print("\nColumns:")
print(len(multimodal.columns))

display(
    multimodal.head()
)

======================================================================
MASTER DATASET
======================================================================
Shape:
(357, 1024)

Columns:
1024

,patient_id,file_uuid,years_to_birth,Tumor_purity,pathologic_stage,pathology_T_stage,pathology_N_stage,pathology_M_stage,number_of_lymph_nodes,radiation_therapy,...,SLC1A6,PTGDS,TFCP2L1,ZIC5,CRYAB,EMILIN3,TNNT2,INA,event,survival_time
0,TCGA-AC-A3BB,00ab866f-a0a3-44c0-ad14-c9dc833239a7,-0.962155,-1.473020,3,3,2,0,0.663363,1,...,-0.365232,1.614857,-0.969645,-0.384022,0.737494,0.452037,-0.530162,0.002997,0,987.0
1,TCGA-A8-A06O,01c79d06-a4a7-47a7-bb8b-b98ce6652c99,0.106767,0.065894,1,1,0,0,-0.269000,0,...,-0.580847,-0.200473,0.987724,1.405035,0.375263,-1.019845,-0.681348,-0.674596,0,396.0
2,TCGA-B6-A0WZ,02732da3-5144-4680-b6ee-cb8563125493,-0.656749,0.958908,2,2,1,0,2.061906,1,...,-0.580847,-0.846220,-0.451058,-0.384022,-0.795755,-0.456894,-1.043650,-0.253540,0,6292.0
3,TCGA-E2-A1L9,0279f555-9738-41e0-b89f-ded25829adc0,-1.420264,0.400312,2,1,1,0,-0.269000,1,...,-0.580847,-0.905408,-1.886017,-0.186071,0.276367,-0.705331,-1.043650,0.034138,0,598.0
4,TCGA-AC-A5XU,032fc1ed-c515-4b26-a229-f67c1eb6fdc3,1.175689,0.375897,2,3,0,0,-0.502090,1,...,-0.351638,-0.997118,-1.802918,-0.599734,-0.579521,-1.000917,-1.043650,-0.338875,0,455.0

In [ ]:
print(multimodal.columns.tolist())

['patient_id', 'file_uuid', 'years_to_birth', 'Tumor_purity', 'pathologic_stage', 'pathology_T_stage', 'pathology_N_stage', 'pathology_M_stage', 'number_of_lymph_nodes', 'radiation_therapy', 'histological_type_infiltratinglobularcarcinoma', 'histological_type_medullarycarcinoma', 'histological_type_metaplasticcarcinoma', 'histological_type_mixedhistology(pleasespecify)', 'histological_type_mucinouscarcinoma', 'histological_type_other,specify', 'PAM50_Her2', 'PAM50_LumA', 'PAM50_LumB', 'race_blackorafricanamerican', 'race_white', 'ethnicity_nothispanicorlatino', 'CLEC3A', 'CPB1', 'SCGB2A2', 'SCGB1D2', 'TFF1', 'GSTM1', 'PIP', 'S100A7', 'MUCL1', 'CYP2B7P1', 'ANKRD30A', 'PRAME', 'CYP4Z1', 'KCNJ3', 'AGR3', 'HMGCS2', 'SERPINA6', 'TFAP2B', 'MUC6', 'DHRS2', 'SLC30A8', 'UGT2B11', 'VSTM2A', 'COL2A1', 'C4orf7', 'TAT', 'ADIPOQ', 'ADH1B', 'CALML5', 'GP2', 'MYBPC1', 'GABRP', 'KRT14', 'CEACAM5', 'MUC5B', 'TFF3', 'C1orf64', 'SOX10', 'GRIA2', 'KRT5', 'CRABP1', 'GSTT1', 'SYT13', 'STAC2', 'CST9', 'LTF', 'KRT6B', 'BMPR1B', 'KLK11', 'HOXB13', 'CYP2A6', 'FABP7', 'NPY1R', 'CEACAM6', 'GFRA1', 'CRISP3', 'ABCC11', 'C20orf114', 'CLCA2', 'KIF1A', 'PVALB', 'LRP2', 'TCN1', 'AGR2', 'OBP2B', 'CP', 'CGA', 'PGR', 'KCNC2', 'SLC34A2', 'OLFM4', 'KRT6A', 'KLK5', 'MUC16', 'CYP4F8', 'PROM1', 'BPIL1', 'KRT16', 'DSG3', 'FAM5C', 'MSLN', 'SLC5A8', 'A2ML1', 'CBLN2', 'SERPINA11', 'NLRP2', 'PIGR', 'PTPRT', 'AQP5', 'KRT81', 'ELF5', 'KRT17', 'CA9', 'VGLL1', 'BEX1', 'CST1', 'TUSC5', 'SLC6A4', 'LBP', 'KLK6', 'KLK10', 'CYP4Z2P', 'PPP1R1B', 'NXPH1', 'SLITRK6', 'KLHDC7A', 'LRRC31', 'ESR1', 'C10orf82', 'PPP2R2C', 'EEF1A2', 'SYT9', 'DCD', 'ANKRD30B', 'SCGB2A1', 'ORM1', 'CALML3', 'GRPR', 'FABP4', 'CHAD', 'TNNT1', 'CST5', 'SORCS1', 'MAGEA6', 'KLK7', 'ASCL1', 'MUC2', 'CLIC6', 'PDZK1', 'CDC20B', 'CXCL17', 'SLC6A14', 'RPS28', 'PEG10', 'DIO1', 'CARTPT', 'FOXI1', 'NBPF4', 'SPAG6', 'PYDC1', 'C7', 'SDR16C5', 'CASP14', 'CNTNAP2', 'ABCC8', 'WNK4', 'MUC15', 'CIDEC', 'LCN2', 'S100A7A', 'PPAN-P2RY11', 'SCUBE2', 'MIA', 'S100A8', 'ABCA12', 'SCGB3A1', 'PGLYRP2', 'FOLR1', 'DSC3', 'C2orf54', 'CAPN8', 'IGSF1', 'MSMB', 'CXCL13', 'S100A9', 'LRP1B', 'MAGEA3', 'SERPINA5', 'TMPRSS4', 'LY6D', 'TRH', 'SERPINB5', 'GLYATL2', 'SLC7A4', 'HS6ST3', 'SLC5A1', 'PON3', 'MMP1', 'ERBB4', 'SLC44A4', 'SFRP1', 'NBPF6', 'PLA2G2A', 'COL17A1', 'ALB', 'ZIC1', 'S100P', 'ROBO2', 'RIMS4', 'ORM2', 'CYP4F22', 'WIF1', 'NEK10', 'NCRNA00052', 'GLRA3', 'TMC5', 'ABCC13', 'IL20', 'ROPN1', 'PI16', 'LPPR3', 'ELOVL2', 'INSM1', 'TSPAN8', 'CCL19', 'SLC9A2', 'SLC7A2', 'LEP', 'PI3', 'LOC728606', 'FREM2', 'MS4A15', 'WFDC2', 'KNDC1', 'FAM3B', 'HGD', 'ATP6V0A4', 'WDR72', 'FGB', 'CAPN6', 'CHST8', 'ATP13A5', 'NKAIN1', 'TRPA1', 'SYT1', 'NCCRP1', 'FAM5B', 'PTPRZ1', 'ANXA8', 'CYP4B1', 'HORMAD1', 'VTCN1', 'FOXJ1', 'CCL21', 'SYTL5', 'KLK8', 'ACTL8', 'PKP1', 'CR2', 'GRB14', 'SPDYC', 'KRT15', 'PLIN1', 'AGTR1', 'CHGB', 'BCAS1', 'C16orf89', 'GLDC', 'TPRG1', 'BBOX1', 'TMPRSS6', 'GPD1', 'HOTAIR', 'CYP4X1', 'TUBA3D', 'ART3', 'SYT8', 'LRG1', 'GPR98', 'NAT1', 'CYP2A7', 'MS4A1', 'FSIP1', 'FAM196A', 'CIDEA', 'GSTA1', 'TRIM29', 'SLPI', 'PROL1', 'NDP', 'DLK1', 'CHIT1', 'ZIC2', 'FLJ45983', 'PAX7', 'ROPN1B', 'SOSTDC1', 'HEPACAM2', 'PPP4R4', 'PCSK1N', 'ALOX15B', 'PNMT', 'ATRNL1', 'IGDCC3', 'CST4', 'TF', 'MARCO', 'PSCA', 'MMP12', 'RGS22', 'ANXA8L2', 'DSG1', 'C2CD4A', 'SLC13A2', 'LOC100271831', 'GPR26', 'AKR7A3', 'ONECUT2', 'GABRB3', 'HOXC11', 'PRODH', 'GJB1', 'KRT23', 'KRT6C', 'RBM24', 'C1orf173', 'C19orf33', 'C3orf57', 'GRIK3', 'FOXA1', 'TRPV6', 'THRSP', 'UGT2B15', 'ARHGAP36', 'DARC', 'SAA2', 'SHISA9', 'KRT4', 'TMPRSS3', 'FUT3', 'VSIG2', 'IGJ', 'POF1B', 'PPP1R14C', 'SAA1', 'VIPR2', 'TPSG1', 'PRSS21', 'TDRD1', 'HBA1', 'PLIN4', 'TFPI2', 'KRT13', 'AREG', 'TTYH1', 'SLC26A3', 'SLC28A3', 'PLCH1', 'MMP13', 'CCNO', 'AR', 'DLX2', 'DKK1', 'CXADRP3', 'SYNPO2L', 'AFF3', 'ATP13A4', 'S100A2', 'AKR1B10', 'PI15', 'SPAG17', 'NTNG1', 'FAM83E', 'SBSN', 'PCDHA11', 'ANKRD43', 'ZNF385B', 'NPY5R', 'F7', 'HSD17B2', 'DCX', 'NELL2', 'MAPK4', 'FGG', 'PCDHA12', 'IYD', 'SOX2', 'MYT1', 'CACNG4', 'DCDC2', 'FAM83A', 'EPYC', 'ADCY5', 'TSIX', 'CHI3L2', 'PHGR1', 'PCDH10', 'WT1', 'SHISA2', 'KCNG1', 'PP14571', 'EDN3', 'HPX', 'RIMS2', 'COL11A1', 'CD177', 'TLX1', 'PCK1', 'GLYATL1', 'CYP4F11', 'SEZ6L', 'LOC642587', 'S100A1', 'TTC36', 'MMP7', 'PART1', 'NEURL', 'TBC1D3G', 'CNTFR', 'GABBR2', 'CRYM', 'TOX3', 'PPP1R1A', 'SCRG1', 'PLA2G2D', 'LGR6', 'RET', 'SLC15A1', 'ZFP57', 'SMOC1', 'HOXC10', 'TUBA3E', 'UGT2B28', 'MKRN3', 'HRASLS5', 'SLC6A11', 'CXCL14', 'CHGA', 'PLA2G3', 'KCNF1', 'RHCG', 'CHRDL1', 'TSPAN1', 'MKX', 'BCL11A', 'FBN3', 'MS4A8B', 'SLC6A15', 'NKX2-2', 'MAGEA1', 'FUT6', 'MAPT', 'CTNND2', 'CPLX2', 'AKR1C2', 'DOK7', 'UGT8', 'PCSK1', 'LOC389033', 'CECR2', 'APOD', 'OGN', 'RASAL1', 'DACH1', 'ABCC12', 'HP', 'TMEM40', 'MMP10', 'CPA6', 'ABCA8', 'FAT2', 'SCNN1G', 'DEFB1', 'LY6K', 'C2orf40', 'SCARA5', 'FGFBP1', 'NOVA1', 'CLGN', 'FGF10', 'SCGN', 'PIK3C2G', 'CCL18', 'RBP4', 'GRM4', 'TPSD1', 'ADAMTS15', 'CD79A', 'C1orf106', 'TNFSF12-TNFSF13', 'FLT3', 'AQP7', 'PAH', 'GPRIN2', 'PLIN5', 'NMU', 'IRX4', 'ADAMTS19', 'SHC4', 'CLSTN2', 'GATA4', 'GJB3', 'B3GNT3', 'FCRL5', 'TMEM132C', 'SLC1A1', 'EMX1', 'PCOLCE2', 'DLGAP1', 'PSAT1', 'MAOB', 'COL9A3', 'AFP', 'ADAM6', 'LOC339535', 'IRX1', 'LOC440905', 'SEMA3E', 'CD300LG', 'SERHL2', 'GNG4', 'CAPN9', 'MYO3B', 'LOC84740', 'PDZK1IP1', 'SLC44A5', 'CXorf61', 'DNALI1', 'HAPLN1', 'PAX2', 'SLC19A3', 'CD19', 'DLX1', 'SPDEF', 'C6', 'SERPINB2', 'MAGEA4', 'IL12RB2', 'UNC5A', 'CAPN13', 'CHRM1', 'COCH', 'PEG3', 'CKMT1A', 'TMEM213', 'FERMT1', 'SPINK8', 'SOX11', 'NELL1', 'PADI3', 'TNNI3', 'CXCL9', 'CHI3L1', 'PCDHA10', 'PTCHD1', 'FUT9', 'CA8', 'LOC145837', 'LRRC26', 'GAL', 'CWH43', 'CA12', 'DNER', 'RNF183', 'L1CAM', 'SLC27A6', 'STC2', 'DPYSL5', 'CDSN', 'ACTA1', 'TRIM58', 'PCDHA6', 'MAGEA2', 'TMEM45B', 'UBD', 'ADAMTS16', 'GATA5', 'FAM184B', 'DEGS2', 'PRG4', 'ANO5', 'C2orf72', 'HHIPL2', 'HPGD', 'FIBCD1', 'KRT7', 'C2orf82', 'PCDHA4', 'ALOX15', 'VWDE', 'EN1', 'DES', 'KCNK15', 'ACTG2', 'TP63', 'ST8SIA6', 'NTS', 'IGFALS', 'ZBTB16', 'LGALS12', 'ABCA13', 'C1orf168', 'B3GALT5', 'IDO1', 'CXCR2P1', 'GPX2', 'GPR110', 'DBC1', 'PTPN20B', 'EREG', 'KRT75', 'GRIA1', 'SPIB', 'NTRK3', 'SCUBE1', 'SAMD11', 'C1orf95', 'S100B', 'NKX2-5', 'TMEM150C', 'ANO3', 'TCL1A', 'VWA2', 'SLC27A2', 'LIN7A', 'ACE2', 'RASSF10', 'PEBP4', 'NCAM2', 'AMY1A', 'MAT1A', 'MAPK15', 'ATP6V1B1', 'XAGE1D', 'VSTM2L', 'NLRP5', 'ACTN2', 'CDH19', 'FAM3D', 'LRTM2', 'C8orf85', 'MGAM', 'KCNH1', 'SLC12A1', 'RTBDN', 'MLPH', 'LOC96610', 'DPY19L2P4', 'DNAJC12', 'CHST9', 'UGT2B4', 'SIX3', 'SP5', 'C10orf81', 'OSR1', 'SCAND3', 'KLK14', 'LONRF2', 'HOXC13', 'GPM6A', 'THBS4', 'MT1G', 'MYEOV', 'ARX', 'SCEL', 'CYP24A1', 'CLDN8', 'UPK1A', 'MAGEA12', 'TCAM1P', 'CACNG6', 'COL4A6', 'GRP', 'RIMS1', 'ADAMDEC1', 'BRSK2', 'GREB1', 'GPR12', 'RP1', 'PLP1', 'DNAH11', 'PRR15', 'CPA3', 'KCND3', 'CSAG3', 'POU2AF1', 'ZMAT4', 'FAM135B', 'CST2', 'LOC100128977', 'ABHD12B', 'AKR1B15', 'FAM83B', 'AK5', 'MUM1L1', 'RANBP3L', 'FLRT3', 'SCNN1B', 'ADCY2', 'CACNG1', 'SLC30A2', 'AP3B2', 'IL6ST', 'CALB2', 'PCDHA1', 'FOXD1', 'PHYHD1', 'TUBB2B', 'TIMP4', 'SPESP1', 'PNCK', 'CITED1', 'SERPINB7', 'SULT4A1', 'SUSD3', 'GAD1', 'CADM3', 'SELP', 'PLAC2', 'MNX1', 'ATP1A2', 'UGT1A6', 'GPR158', 'SMC1B', 'ALDH3B2', 'IVL', 'CACNA1H', 'PHF21B', 'TNS4', 'TYRP1', 'C1orf116', 'LOC150622', 'ADH1C', 'LOC389493', 'C19orf21', 'EGF', 'AQP9', 'KLK12', 'CD1A', 'LPAR3', 'TMEM145', 'GJB5', 'LOC100130148', 'ALDH1L1', 'PTX3', 'SLITRK5', 'MSI1', 'CXCL1', 'XDH', 'SCUBE3', 'ADCY1', 'CKMT1B', 'KCNK3', 'B4GALNT2', 'SIX1', 'GJB6', 'EHF', 'WDR17', 'ALOX12P2', 'KLK13', 'UPF0639', 'CORO6', 'DQX1', 'P2RY11', 'C21orf15', 'SCN7A', 'BMP7', 'PCSK2', 'ENTPD8', 'AGT', 'AMBP', 'GREB1L', 'ATP1A4', 'SLC16A6', 'RELN', 'PRSS12', 'HPN', 'RIC3', 'TMEM84', 'MMP3', 'LOC153328', 'LY6G6C', 'KCNE4', 'SLC35F3', 'TBX1', 'FGFR4', 'HOXB5', 'KLK4', 'AQP3', 'WISP3', 'LOC152225', 'C6orf141', 'CXCL5', 'MGC29506', 'PCDHA13', 'C6orf15', 'PITX1', 'CAPSL', 'HRASLS', 'KCNK2', 'NPW', 'C14orf180', 'SOX8', 'CES3', 'CAMK2B', 'CUX2', 'CT62', 'DUSP9', 'EPHA8', 'KRT31', 'NXNL2', 'RERGL', 'KIAA0125', 'ACMSD', 'TDRD9', 'FABP6', 'DAPL1', 'ADCYAP1', 'CYP4F12', 'CFB', 'GSDMC', 'KIF12', 'HMP19', 'KCNK1', 'BLK', 'WNT6', 'CLEC10A', 'RARRES1', 'CSN3', 'PCDHGB5', 'ARMC3', 'C1orf130', 'KRT86', 'CPA4', 'CHRDL2', 'TNFRSF17', 'GZMB', 'HRCT1', 'ITIH5L', 'LRAT', 'C4A', 'FAIM2', 'SERPINA3', 'GRIA4', 'TDRD12', 'LYPD6', 'COMP', 'CD38', 'PTPRN2', 'CRTAC1', 'TARP', 'FOSB', 'SMYD1', 'SMR3B', 'AKR1C1', 'C9orf152', 'NME5', 'LGALS7B', 'GPT', 'MT1A', 'IL33', 'RNF212', 'PRSS16', 'STEAP4', 'TPSB2', 'ACOX2', 'CHODL', 'CTSG', 'CNTN1', 'C4BPA', 'REEP6', 'CILP', 'KISS1R', 'TGM3', 'C8orf84', 'OXGR1', 'SRPK3', 'ARC', 'PRKAA2', 'IBSP', 'ATP1A3', 'CAMP', 'STK32B', 'IL7R', 'CCL28', 'SLC4A10', 'PGC', 'HS6ST2', 'AZGP1', 'PYY', 'BAIAP3', 'KIAA0408', 'MRAP', 'SFTPA2', 'FOXA3', 'CRHR1', 'MOGAT2', 'GPR87', 'CPNE4', 'GFRA3', 'CHRNA9', 'CCL14', 'TMEM139', 'ODZ2', 'SLIT1', 'NPY2R', 'ITGB6', 'GLB1L2', 'SPINK5', 'HMGCLL1', 'SNORD116-4', 'FGFR3', 'CRISPLD1', 'SPRR3', 'ABP1', 'LMO3', 'GZMK', 'LRRN1', 'RUNDC3A', 'LGALS7', 'ALG1L', 'EYA1', 'CD36', 'ACCN1', 'GGT6', 'ABCA4', 'IGSF21', 'BARX1', 'BPI', 'KLRG2', 'FAM189A1', 'PXDNL', 'ECEL1', 'FCER2', 'OGDHL', 'GABRE', 'TNN', 'PLEKHG4B', 'IL20RA', 'MUC13', 'SDK2', 'LTB', 'TNNT3', 'GNG13', 'LACRT', 'SYT5', 'C6orf223', 'KIAA0319', 'KLHDC7B', 'MESP1', 'MUC7', 'LEFTY2', 'KCNH2', 'CYP26A1', 'PCDH20', 'COL22A1', 'CST6', 'PCDHGB1', 'NRK', 'ZMYND10', 'FMO2', 'GDF15', 'CYP21A2', 'LAMC2', 'MAG', 'NRXN1', 'GRAMD2', 'PRSS33', 'FCRL3', 'PCP4L1', 'MAP7D2', 'LGR5', 'FXYD1', 'CES1', 'CDH7', 'VIT', 'PNPLA3', 'LEMD1', 'DPP10', 'HDC', 'IL6', 'CACNA2D1', 'ZPLD1', 'CCDC129', 'LDHC', 'LOC284379', 'KLHL1', 'C20orf85', 'CHRNB2', 'MMRN1', 'EDIL3', 'PEX5L', 'MLC1', 'psiTPTE22', 'BMP5', 'MAGEC2', 'CXCL11', 'PLA2G10', 'TGM5', 'CD207', 'COL11A2', 'SNAP25', 'CDCA7', 'CLDN10', 'OBP2A', 'ENHO', 'EPHA7', 'B3GAT1', 'COL10A1', 'CRLF1', 'DNAH5', 'DMKN', 'SLC1A6', 'PTGDS', 'TFCP2L1', 'ZIC5', 'CRYAB', 'EMILIN3', 'TNNT2', 'INA', 'event', 'survival_time']

##Dataset Quality Control

In [ ]:
# ============================================================
# DATASET QUALITY CONTROL
# ============================================================

print("="*70)
print("QUALITY CONTROL")
print("="*70)


print("Patients:")
print(
    multimodal["patient_id"].nunique()
)


print("\nRows:")
print(
    len(multimodal)
)


print("\nDuplicate patients:")
print(
    multimodal["patient_id"].duplicated().sum()
)


print("\nMissing RFS event:")
print(
    multimodal["event"].isna().sum()
)


print("\nMissing RFS time:")
print(
    multimodal["survival_time"].isna().sum()
)


print("\nMissing pathology UUID:")
print(
    multimodal["file_uuid"].isna().sum()
)


print("\nRFS event distribution:")
print(
    multimodal["event"].value_counts()
)

======================================================================
QUALITY CONTROL
======================================================================
Patients:
357

Rows:
357

Duplicate patients:
0

Missing RFS event:
0

Missing RFS time:
0

Missing pathology UUID:
0

RFS event distribution:
event
0    266
1     91
Name: count, dtype: int64

##Fix Random Seed

In [ ]:
# ============================================================
# RANDOM SEED
# ============================================================

RANDOM_SEED = 42

random.seed(RANDOM_SEED)

np.random.seed(RANDOM_SEED)

print("="*70)
print("RANDOM SEED")
print("="*70)

print(RANDOM_SEED)

======================================================================
RANDOM SEED
======================================================================
42

##Stratified Dataset Split

In [ ]:
# ============================================================
# STRATIFIED TRAIN / VALIDATION / TEST SPLIT
# ============================================================

print("="*70)
print("CREATING DATASET SPLITS")
print("="*70)


train_df, temp_df = train_test_split(

    multimodal,

    test_size=0.30,

    stratify=multimodal["event"],

    random_state=RANDOM_SEED
)



validation_df, test_df = train_test_split(

    temp_df,

    test_size=0.50,

    stratify=temp_df["event"],

    random_state=RANDOM_SEED
)



print("Train:")
print(train_df.shape)

print()

print("Validation:")
print(validation_df.shape)

print()

print("Test:")
print(test_df.shape)

======================================================================
CREATING DATASET SPLITS
======================================================================
Train:
(249, 1024)

Validation:
(54, 1024)

Test:
(54, 1024)

##Verify Split

In [ ]:
# ============================================================
# VERIFY DATASET SPLITS
# ============================================================

print("=" * 70)
print("VERIFYING DATASET SPLITS")
print("=" * 70)


def summarize_split(df, name):

    total = len(df)

    events = int(df["event"].sum())

    non_events = total - events

    ratio = events / total

    print(f"\n{name}")

    print("-" * 40)

    print(f"Patients      : {total}")

    print(f"Events        : {events}")

    print(f"Non-events    : {non_events}")

    print(f"Event Ratio   : {ratio:.4f}")


summarize_split(train_df, "TRAIN")

summarize_split(validation_df, "VALIDATION")

summarize_split(test_df, "TEST")

======================================================================
VERIFYING DATASET SPLITS
======================================================================

TRAIN
----------------------------------------
Patients      : 249
Events        : 63
Non-events    : 186
Event Ratio   : 0.2530

VALIDATION
----------------------------------------
Patients      : 54
Events        : 14
Non-events    : 40
Event Ratio   : 0.2593

TEST
----------------------------------------
Patients      : 54
Events        : 14
Non-events    : 40
Event Ratio   : 0.2593

##Save Train Dataset

In [ ]:
# ============================================================
# SAVE TRAIN DATASET
# ============================================================

train_path = os.path.join(
    SAVE_DIR,
    "train_rfs.csv"
)

train_df.to_csv(
    train_path,
    index=False
)

print("=" * 70)
print("TRAIN DATASET SAVED")
print("=" * 70)

print(train_path)

======================================================================
TRAIN DATASET SAVED
======================================================================
/content/drive/MyDrive/TCGA_BRCA/dataset_split_rfs/train_rfs.csv

##Save Validation Dataset

In [ ]:
# ============================================================
# SAVE VALIDATION DATASET
# ============================================================

validation_path = os.path.join(
    SAVE_DIR,
    "validation_rfs.csv"
)

validation_df.to_csv(
    validation_path,
    index=False
)

print("=" * 70)
print("VALIDATION DATASET SAVED")
print("=" * 70)

print(validation_path)

======================================================================
VALIDATION DATASET SAVED
======================================================================
/content/drive/MyDrive/TCGA_BRCA/dataset_split_rfs/validation_rfs.csv

##Save Test Dataset

In [ ]:
# ============================================================
# SAVE TEST DATASET
# ============================================================

test_path = os.path.join(
    SAVE_DIR,
    "test_rfs.csv"
)

test_df.to_csv(
    test_path,
    index=False
)

print("=" * 70)
print("TEST DATASET SAVED")
print("=" * 70)

print(test_path)

======================================================================
TEST DATASET SAVED
======================================================================
/content/drive/MyDrive/TCGA_BRCA/dataset_split_rfs/test_rfs.csv

##Save Patient ID Lists

In [ ]:
# ============================================================
# SAVE PATIENT ID LISTS
# ============================================================

train_df[["patient_id"]].to_csv(
    os.path.join(SAVE_DIR, "train_rfs_patient_ids.csv"),
    index=False
)

validation_df[["patient_id"]].to_csv(
    os.path.join(SAVE_DIR, "validation_rfs_patient_ids.csv"),
    index=False
)

test_df[["patient_id"]].to_csv(
    os.path.join(SAVE_DIR, "test_rfs_patient_ids.csv"),
    index=False
)

print("=" * 70)
print("PATIENT ID LISTS SAVED")
print("=" * 70)

print(os.listdir(SAVE_DIR))

======================================================================
PATIENT ID LISTS SAVED
======================================================================
['train_rfs.csv', 'validation_rfs.csv', 'test_rfs.csv', 'train_rfs_patient_ids.csv', 'validation_rfs_patient_ids.csv', 'test_rfs_patient_ids.csv']

##Save Split Statistics

In [ ]:
# ============================================================
# SAVE SPLIT STATISTICS
# ============================================================

statistics = pd.DataFrame({
    "Split": [
        "Train",
        "Validation",
        "Test"
    ],
    "Patients": [
        len(train_df),
        len(validation_df),
        len(test_df)
    ],
    "Events": [
        int(train_df["event"].sum()),
        int(validation_df["event"].sum()),
        int(test_df["event"].sum())
    ],
    "Non_events": [
        len(train_df) - int(train_df["event"].sum()),
        len(validation_df) - int(validation_df["event"].sum()),
        len(test_df) - int(test_df["event"].sum())
    ],
    "RFS_event_ratio": [
        train_df["event"].mean(),
        validation_df["event"].mean(),
        test_df["event"].mean()
    ]
})

statistics.to_csv(
    os.path.join(
        SAVE_DIR,
        "rfs_split_statistics.csv"
    ),
    index=False
)

print("=" * 70)
print("SPLIT STATISTICS")
print("=" * 70)

display(statistics)

======================================================================
SPLIT STATISTICS
======================================================================

        Split  Patients  Events  Non_events  RFS_event_ratio
0       Train       249      63         186         0.253012
1  Validation        54      14          40         0.259259
2        Test        54      14          40         0.259259

##Final Validation

In [ ]:
# ============================================================
# FINAL VALIDATION
# ============================================================

print("=" * 70)
print("FINAL VALIDATION")
print("=" * 70)

all_patients = (
    set(train_df["patient_id"])
    |
    set(validation_df["patient_id"])
    |
    set(test_df["patient_id"])
)

train_val_overlap = (
    set(train_df["patient_id"])
    &
    set(validation_df["patient_id"])
)

train_test_overlap = (
    set(train_df["patient_id"])
    &
    set(test_df["patient_id"])
)

validation_test_overlap = (
    set(validation_df["patient_id"])
    &
    set(test_df["patient_id"])
)

print("Unique patients:", len(all_patients))

print("\nTrain duplicates:",
      train_df["patient_id"].duplicated().sum())

print("Validation duplicates:",
      validation_df["patient_id"].duplicated().sum())

print("Test duplicates:",
      test_df["patient_id"].duplicated().sum())

print("\nTrain ↔ Validation overlap:",
      len(train_val_overlap))

print("Train ↔ Test overlap:",
      len(train_test_overlap))

print("Validation ↔ Test overlap:",
      len(validation_test_overlap))

print("\nMissing events:")

print(
    train_df["event"].isna().sum() +
    validation_df["event"].isna().sum() +
    test_df["event"].isna().sum()
)

print("\nMissing survival:")

print(
    train_df["survival_time"].isna().sum() +
    validation_df["survival_time"].isna().sum() +
    test_df["survival_time"].isna().sum()
)

======================================================================
FINAL VALIDATION
======================================================================
Unique patients: 357

Train duplicates: 0
Validation duplicates: 0
Test duplicates: 0

Train ↔ Validation overlap: 0
Train ↔ Test overlap: 0
Validation ↔ Test overlap: 0

Missing events:
0

Missing survival:
0

##Notebook Summary

In [ ]:
# ============================================================
# DATASET SPLIT SUMMARY
# ============================================================

print("=" * 70)
print("DATASET SPLITTING COMPLETED")
print("=" * 70)

print(f"Master dataset        : {len(multimodal)} patients")

print(f"Training set          : {len(train_df)}")

print(f"Validation set        : {len(validation_df)}")

print(f"Testing set           : {len(test_df)}")

print(f"RFS recurrence events : {multimodal['event'].sum()}")

print(f"Random seed           : {RANDOM_SEED}")

print(f"Split strategy        : Stratified")

print(f"Train ratio           : 70%")

print(f"Validation ratio      : 15%")

print(f"Test ratio            : 15%")

print("\nOutput directory:")

print(SAVE_DIR)

print("\nNotebook completed successfully.")

======================================================================
DATASET SPLITTING COMPLETED
======================================================================
Master dataset        : 357 patients
Training set          : 249
Validation set        : 54
Testing set           : 54
RFS recurrence events : 91
Random seed           : 42
Split strategy        : Stratified
Train ratio           : 70%
Validation ratio      : 15%
Test ratio            : 15%

Output directory:
/content/drive/MyDrive/TCGA_BRCA/dataset_split_rfs

Notebook completed successfully.